import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,mkdtempSync,rmSync} from 'node:fs';
import {createRequire} from 'node:module';
import {pathToFileURL,fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);
const {Window}=await import('happy-dom');
const window=new Window();for(const key of ['window','document','HTMLElement','HTMLInputElement','Event','MouseEvent','Node'])globalThis[key]=key==='window'?window:window[key];
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{createRoot}=require('react-dom/client');const {act}=React;
const componentFile=new URL('../src/client/BudgetSettingsSection.tsx',import.meta.url);
let Component;
if(existsSync(componentFile)){
 const esbuild=await import('esbuild');const runtime=mkdtempSync(fileURLToPath(new URL('./.runtime-',import.meta.url)));const output=runtime+'/component.mjs';after(()=>{window.close();rmSync(runtime,{recursive:true,force:true});});
 await esbuild.build({entryPoints:[fileURLToPath(componentFile)],outfile:output,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime'],loader:{'.css':'empty'},tsconfigRaw:{compilerOptions:{jsx:'react-jsx'}}});
 Component=(await import(pathToFileURL(output))).BudgetSettingsSection;
}
const list=()=>({version:1,available:true,reason:null,defaults:{limitCny:100,revision:3},shared:{limitCny:100,accountedUpperBoundCny:30,remainingCny:70},taskLimitCny:5,sessions:[{id:'root-1',label:'First window'},{id:'root-2',label:'Second window'}]});
const snapshot=(id='root-1')=>({version:1,rootSessionId:id,limitCny:100,revision:4,usesDefault:true,accountedUpperBoundCny:2,settledCny:1.5,reservedCny:.5,remainingCny:98,unattributedSharedCny:28,isProviderInvoice:false});
const api=()=>({list:async()=>list(),get:async id=>snapshot(id),update:async(id,v,r)=>({...snapshot(id),limitCny:v,revision:r+1,usesDefault:false}),updateDefault:async(v,r)=>({limitCny:v,revision:r+1})});
async function mount(service=api(),timeout=1000){assert.equal(typeof Component,'function','budget settings component is implemented');const div=document.createElement('div');document.body.append(div);const root=createRoot(div);await act(async()=>{root.render(React.createElement(Component,{api:service,requestTimeoutMs:timeout,useConnection:()=>0,t:k=>k,close:()=>{}}));await new Promise(r=>setTimeout(r,10));});return {div,root,cleanup:async()=>{await act(async()=>root.unmount());div.remove();}};}
async function input(node,value){await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));});}
async function click(node){assert.ok(node);await act(async()=>{node.dispatchEvent(new MouseEvent('click',{bubbles:true}));await new Promise(r=>setTimeout(r,10));});}
const button=(div,key)=>[...div.querySelectorAll('button')].find(x=>x.textContent===key);
test('settings shows default 100, separate shared/task guards and session usage',async()=>{const v=await mount();try{assert.equal(v.div.querySelector('[name=defaultLimit]').value,'100');assert.equal(v.div.querySelector('[name=sessionLimit]').value,'100');assert.match(v.div.textContent,/notInvoice/);assert.match(v.div.textContent,/sharedGuard/);assert.match(v.div.textContent,/taskGuard/);assert.match(v.div.textContent,/2\.00/);}finally{await v.cleanup();}});
test('default edit carries existing revision without clearing spend',async()=>{let received;const service=api();service.updateDefault=async(...args)=>{received=args;return {limitCny:250,revision:4}};const v=await mount(service);try{await input(v.div.querySelector('[name=defaultLimit]'),'250');await click(button(v.div,'saveDefault'));assert.equal(received[0],250);assert.equal(received[1],3);assert.match(v.div.textContent,/2\.00/);}finally{await v.cleanup();}});
test('window override binds chosen session and revision',async()=>{let received;const service=api();service.update=async(...args)=>{received=args;return {...snapshot(),limitCny:12.34,revision:5,usesDefault:false}};const v=await mount(service);try{await input(v.div.querySelector('[name=sessionLimit]'),'12.34');await click(button(v.div,'saveSession'));assert.equal(received[0],'root-1');assert.equal(received[1],12.34);assert.equal(received[2],4);}finally{await v.cleanup();}});
test('zero and sub-cent guard values cannot be submitted',async()=>{let calls=0;const service=api();service.updateDefault=async()=>{calls++};const v=await mount(service);try{for(const value of ['0','0.001','1000000.01','-1','']){await input(v.div.querySelector('[name=defaultLimit]'),value);assert.equal(button(v.div,'saveDefault').disabled,true);}assert.equal(calls,0);}finally{await v.cleanup();}});
test('ambiguous save result reloads state and never retries mutation',async()=>{let writes=0,reads=0;const service=api();service.get=async id=>{reads++;return snapshot(id)};service.update=async()=>{writes++;throw new Error('network')};const v=await mount(service);try{await input(v.div.querySelector('[name=sessionLimit]'),'15');await click(button(v.div,'saveSession'));assert.equal(writes,1);assert.ok(reads>=2);assert.match(v.div.textContent,/unconfirmed/);}finally{await v.cleanup();}});
test('conflict is shown and canonical state is reread',async()=>{const service=api();service.updateDefault=async()=>{throw new Error('BUDGET_SETTINGS_CONFLICT')};const v=await mount(service);try{await input(v.div.querySelector('[name=defaultLimit]'),'150');await click(button(v.div,'saveDefault'));assert.match(v.div.textContent,/conflict/);assert.equal(v.div.querySelector('[name=defaultLimit]').value,'100');}finally{await v.cleanup();}});
test('unavailable service disables both guard editors',async()=>{const service=api();service.list=async()=>({...list(),available:false,reason:'BUDGET_SETTINGS_UNAVAILABLE',sessions:[]});const v=await mount(service);try{assert.equal(v.div.querySelector('[name=defaultLimit]'),null);assert.equal(v.div.querySelector('[name=sessionLimit]'),null);assert.match(v.div.textContent,/unavailable/);}finally{await v.cleanup();}});
test('bounded write timeout stops UI waiting and reloads without repeat',async()=>{let writes=0;const service=api();service.update=()=>{writes++;return new Promise(()=>{})};const v=await mount(service,20);try{await input(v.div.querySelector('[name=sessionLimit]'),'15');await click(button(v.div,'saveSession'));await act(async()=>{await new Promise(r=>setTimeout(r,40));});assert.equal(writes,1);assert.match(v.div.textContent,/unconfirmed/);assert.equal(button(v.div,'refresh').disabled,false);}finally{await v.cleanup();}});

test('default change rereads the selected session revision before a window override',async()=>{let changed=false,received;const service=api();service.list=async()=>({...list(),defaults:{limitCny:changed?200:100,revision:changed?4:3}});service.get=async id=>({...snapshot(id),limitCny:changed?200:100,revision:changed?5:4});service.updateDefault=async()=>{changed=true;return {limitCny:200,revision:4}};service.update=async(...args)=>{received=args;return {...snapshot(),limitCny:50,revision:6}};const v=await mount(service);try{await input(v.div.querySelector('[name=defaultLimit]'),'200');await click(button(v.div,'saveDefault'));assert.equal(v.div.querySelector('[name=sessionLimit]').value,'200');await input(v.div.querySelector('[name=sessionLimit]'),'50');await click(button(v.div,'saveSession'));assert.equal(received[2],5);}finally{await v.cleanup();}});
test('selecting a second window uses its ID and does not retain prior window values',async()=>{let received;const service=api();service.get=async id=>({...snapshot(id),limitCny:id==='root-2'?20:100});service.update=async(...args)=>{received=args;return {...snapshot('root-2'),limitCny:25}};const v=await mount(service);try{await act(async()=>{const select=v.div.querySelector('select');select.value='root-2';select.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,10));});assert.equal(v.div.querySelector('[name=sessionLimit]').value,'20');await input(v.div.querySelector('[name=sessionLimit]'),'25');await click(button(v.div,'saveSession'));assert.equal(received[0],'root-2');}finally{await v.cleanup();}});
test('unmount aborts its pending read without late rendering',async()=>{let resolveRead,signal;const service=api();service.list=s=>{signal=s;return new Promise(resolve=>{resolveRead=resolve})};const v=await mount(service);await v.cleanup();assert.equal(signal.aborted,true);await act(async()=>{resolveRead(list());await new Promise(r=>setTimeout(r,5));});assert.equal(v.div.childNodes.length,0);});
test('unmount clears a timeout even when the cancelled provider never settles',async()=>{const originalSet=globalThis.setTimeout,originalClear=globalThis.clearTimeout,owned=new Set();globalThis.setTimeout=(fn,ms,...args)=>{const id=originalSet(()=>{owned.delete(id);fn(...args)},ms);owned.add(id);return id};globalThis.clearTimeout=id=>{owned.delete(id);originalClear(id)};try{const service=api();service.list=()=>new Promise(()=>{});const v=await mount(service);await v.cleanup();assert.equal(owned.size,0,'no budget request deadline may outlive the unmounted section');}finally{for(const id of owned)originalClear(id);globalThis.setTimeout=originalSet;globalThis.clearTimeout=originalClear;}});

test('missing ledger after a successful read hides prior amounts and keeps refresh available',async()=>{const service=api();const v=await mount(service);try{assert.match(v.div.textContent,/2\.00/);service.list=async()=>{throw new Error('BUDGET_LEDGER_MISSING')};await click(button(v.div,'refresh'));assert.match(v.div.querySelector('[role=alert]').textContent,/ledgerMissing/);assert.equal(v.div.querySelector('[name=defaultLimit]'),null);assert.equal(v.div.querySelector('[name=sessionLimit]'),null);assert.doesNotMatch(v.div.textContent,/2\.00|70\.00|98\.00/);assert.equal(button(v.div,'refresh').disabled,false);}finally{await v.cleanup();}});

test('cold missing ledger explicitly denies guessing a zero balance',async()=>{const service=api();service.list=async()=>{throw new Error('BUDGET_LEDGER_MISSING')};const v=await mount(service);try{assert.match(v.div.textContent,/ledgerMissing/);assert.equal(v.div.querySelector('input'),null);assert.equal(v.div.querySelector('dd'),null);assert.equal(button(v.div,'refresh').disabled,false);}finally{await v.cleanup();}});

test('missing ledger on save and readback is not retried or represented as saved',async()=>{let writes=0;const service=api();const v=await mount(service);try{service.update=async()=>{writes++;throw new Error('BUDGET_LEDGER_MISSING')};service.list=async()=>{throw new Error('BUDGET_LEDGER_MISSING')};await input(v.div.querySelector('[name=sessionLimit]'),'15');await click(button(v.div,'saveSession'));assert.equal(writes,1);assert.match(v.div.textContent,/ledgerMissing/);assert.equal(v.div.querySelector('input'),null);assert.equal(button(v.div,'refresh').disabled,false);}finally{await v.cleanup();}});

test('Chinese and English missing-ledger messages describe restore and prohibit reset',async()=>{const {zh,en}=await import('../src/client/budget-locales.ts');assert.match(zh.ledgerMissing??'',/预算账本缺失/);assert.match(zh.ledgerMissing??'',/阻止.*模型请求/);assert.match(zh.ledgerMissing??'',/恢复|核验/);assert.match(zh.ledgerMissing??'',/不能清零重建/);assert.match(en.ledgerMissing??'',/missing/i);assert.match(en.ledgerMissing??'',/restore|verify/i);});

test('changed ledger mutation is not repeated and retains a specific notice after successful readback',async()=>{let writes=0;const service=api();service.updateDefault=async()=>{writes++;throw new Error('BUDGET_LEDGER_CHANGED')};const v=await mount(service);try{await input(v.div.querySelector('[name=defaultLimit]'),'150');await click(button(v.div,'saveDefault'));assert.equal(writes,1);assert.match(v.div.textContent,/ledgerChanged/);assert.equal(v.div.querySelector('[name=defaultLimit]').value,'100');}finally{await v.cleanup();}});
test('changed ledger locales describe rejected write and verification',async()=>{const {zh,en}=await import('../src/client/budget-locales.ts');assert.match(zh.ledgerChanged??'',/账本.*变化/);assert.match(zh.ledgerChanged??'',/拒绝.*写入/);assert.match(en.ledgerChanged??'',/changed/i);});
