import test from 'node:test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';
const url=new URL('../src/client/budget-api.ts',import.meta.url);const factory=existsSync(url)?(await import(url)).createBudgetSettingsApi:undefined;
const snap={version:1,rootSessionId:'a',limitCny:100,revision:0,usesDefault:true,accountedUpperBoundCny:3,settledCny:2,reservedCny:1,remainingCny:97,unattributedSharedCny:5,isProviderInvoice:false};
function api(value,record=()=>{}){assert.equal(typeof factory,'function','budget API exists');return factory({call:async(...args)=>{record(args);return {ok:true,value}}});}
test('API transmits exact session override and revision to the owned endpoint',async()=>{let sent;await api(snap,v=>sent=v).update('a',25,0);assert.deepEqual(sent.slice(0,3),['/api','sep-budget/update',{sessionId:'a',limitCny:25,expectedRevision:0}]);});
test('API rejects a different returned session instead of showing foreign budget',async()=>{await assert.rejects(()=>api({...snap,rootSessionId:'b'}).get('a'),/BUDGET_SETTINGS_RESPONSE/);});
test('API rejects malformed or nonfinite returned financial values',async()=>{for(const mutation of [{limitCny:NaN},{remainingCny:Infinity},{accountedUpperBoundCny:-1},{isProviderInvoice:true},{revision:-1}])await assert.rejects(()=>api({...snap,...mutation}).get('a'),/BUDGET_SETTINGS_RESPONSE/);});
test('API accepts negative remaining balance for a guard lowered below spend',async()=>{assert.equal((await api({...snap,limitCny:1,remainingCny:-2}).get('a')).remainingCny,-2);});
test('API rejects duplicate session identifiers',async()=>{const value={version:1,available:true,reason:null,defaults:{limitCny:100,revision:0},shared:{limitCny:100,accountedUpperBoundCny:3,remainingCny:97},taskLimitCny:5,sessions:[{id:'a',label:'a'},{id:'a',label:'b'}]};await assert.rejects(()=>api(value).list(),/BUDGET_SETTINGS_RESPONSE/);});
test('API redacts unowned errors while retaining a safe conflict code',async()=>{assert.equal(typeof factory,'function');for(const [message,want] of [['private text','BUDGET_SETTINGS_UNAVAILABLE'],['BUDGET_SETTINGS_CONFLICT','BUDGET_SETTINGS_CONFLICT']])await assert.rejects(()=>factory({call:async()=>({ok:false,error:{message}})}).list(),new RegExp(want));});
test('unavailable P1 service is represented without fabricated budget fields',async()=>{const value=await api({version:1,available:false,reason:'BUDGET_SETTINGS_UNAVAILABLE',sessions:[]}).list();assert.equal(value.available,false);assert.equal('defaults' in value,false);assert.equal('shared' in value,false);assert.equal('taskLimitCny' in value,false);});
test('real SEP unavailable service crosses Host bridge and client parser without invented amounts',async()=>{const {createBudgetSettingsService}=await import('../../../sep/system-enhancement-package/src/budget-settings-service.js');const {apply}=await import('../src/index.ts');const routes=new Map(),service=createBudgetSettingsService({ctx:{get:()=>null}});apply({get:key=>({connection:{fetch:{register:value=>routes.set(value.path,value)}},suiteEnhancements:{budgetSettings:service},sepDesktopTransport:{kind:'electron-owned-pipe'}})[key]});const settings=factory({call:async(_base,method,payload)=>{const response=await routes.get('/api/'+method).fetch(new Request('dsh-app://app/api/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId:'real-unavailable',method,payload})}));return (await response.json()).result;}});const result=await settings.list();assert.equal(result.available,false);assert.equal(result.reason,'BUDGET_SETTINGS_UNAVAILABLE');assert.equal('defaults' in result,false);assert.equal('shared' in result,false);});

test('API preserves missing ledger guard while redacting unrelated diagnostics',async()=>{await assert.rejects(()=>factory({call:async()=>({ok:false,error:{message:'BUDGET_LEDGER_MISSING'}})}).list(),/^Error: BUDGET_LEDGER_MISSING$/);});

test('API retains ledger changed code without exposing unexpected detail',async()=>{await assert.rejects(()=>factory({call:async()=>({ok:false,error:{message:'BUDGET_LEDGER_CHANGED'}})}).updateDefault(100,0),/^Error: BUDGET_LEDGER_CHANGED$/);});
