import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validateArchive } from '../archive.js';
import { zip, docx } from './zip-fixture.mjs';
const options={maxArchiveEntries:20,maxUncompressedBytes:10000};
const valid=[['[Content_Types].xml','<Types/>'],['word/document.xml','<document/>']];
const check=(bytes,limits=options)=>validateArchive(bytes,'.docx',limits,new AbortController().signal);
test('ordinary stored and deflated OOXML pass structural checks',async()=>{await check(docx());await check(zip(valid,{deflate:true}));});
test('random or truncated ZIP is rejected',async()=>{await assert.rejects(check(Buffer.from('bad')),e=>e.code==='invalid-document');await assert.rejects(check(docx().subarray(0,-8)),e=>e.code==='invalid-document');});
test('declared archive entry limit is enforced',async()=>{await assert.rejects(check(docx(),{...options,maxArchiveEntries:2}),e=>e.code==='input-too-large');});
test('declared uncompressed byte limit is enforced',async()=>{await assert.rejects(check(docx(),{...options,maxUncompressedBytes:8}),e=>e.code==='input-too-large');});
for(const name of ['../outside','/absolute','C:/drive','a\\b','word/../../bad'])test(`reject unsafe entry ${name}`,async()=>{await assert.rejects(check(zip([...valid,[name,'bad']])),e=>e.code==='invalid-document');});
test('case-insensitive duplicate entry is rejected',async()=>{await assert.rejects(check(zip([...valid,['WORD/document.xml','other']])),e=>e.code==='invalid-document');});
test('local and central filenames must agree',async()=>{const bytes=zip(valid);bytes[30]=65;await assert.rejects(check(bytes),e=>e.code==='invalid-document');});
test('CRC mismatch is rejected before LibreOffice runs',async()=>{const bytes=zip(valid);bytes[30+Buffer.byteLength(valid[0][0])]=88;await assert.rejects(check(bytes),e=>e.code==='invalid-document');});
test('macro project is rejected even inside a nonmacro suffix',async()=>{await assert.rejects(check(zip([...valid,['word/vbaProject.bin','macro']])),e=>e.code==='invalid-document');});
test('external fetch relationships are rejected before rendering',async()=>{await assert.rejects(check(zip([...valid,['word/_rels/document.xml.rels','<Relationships><Relationship TargetMode="External" Target="https://example.invalid/image" /></Relationships>']])),e=>e.code==='invalid-document');});
test('missing main OOXML document is rejected',async()=>{await assert.rejects(check(zip([valid[0]])),e=>e.code==='invalid-document');});
test('encrypted entries are rejected',async()=>{const bytes=zip(valid);bytes.writeUInt16LE(1,6);const central=bytes.indexOf(Buffer.from('504b0102','hex'));bytes.writeUInt16LE(1,central+8);await assert.rejects(check(bytes),e=>e.code==='invalid-document');});
test('deflated payload cannot exceed its declaration',async()=>{const bytes=zip([...valid,['big.xml','a'.repeat(5000)]],{deflate:true});let index=0;while((index=bytes.indexOf(Buffer.from('504b0102','hex'),index))!==-1){if(bytes.subarray(index+46,index+53).toString()==='big.xml'){bytes.writeUInt32LE(10,index+24);const local=bytes.readUInt32LE(index+42);bytes.writeUInt32LE(10,local+22);break;}index+=4;}await assert.rejects(check(bytes),e=>e.code==='invalid-document');});
test('cancelled preflight does not consume the archive',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(validateArchive(docx(),'.docx',options,controller.signal),e=>e.name==='AbortError');});
const rel=(type,target,extra='')=>`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId5" Type="${type}" Target="${target}" TargetMode="External" ${extra}/></Relationships>`;
const hyperlink='http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink';
for(const uri of ['https://example.invalid/a?x=1&amp;y=2','http://127.0.0.1:1234/beacon','mailto:test@example.invalid'])test(`ordinary hyperlink remains convertible: ${uri}`,async()=>{await check(zip([...valid,['word/_rels/document.xml.rels',rel(hyperlink,uri)]]));});
for(const uri of ['file:///C:/secret','javascript:alert(1)','//example.invalid/file','https://user:password@example.invalid/'])test(`unsafe hyperlink rejected: ${uri}`,async()=>{await assert.rejects(check(zip([...valid,['word/_rels/document.xml.rels',rel(hyperlink,uri)]])),e=>e.code==='invalid-document');});
test('external attached template remains rejected',async()=>{await assert.rejects(check(zip([...valid,['word/_rels/document.xml.rels',rel('http://schemas.openxmlformats.org/officeDocument/2006/relationships/attachedTemplate','https://example.invalid/template')]])),e=>e.code==='invalid-document');});
test('XML duplicate attributes cannot disguise an external type',async()=>{await assert.rejects(check(zip([...valid,['word/_rels/document.xml.rels',rel(hyperlink,'https://example.invalid','Type="unsafe"')]])),e=>e.code==='invalid-document');});
test('UTF16 without BOM cannot evade external relationship checks',async()=>{const bytes=Buffer.from(rel('external-image','https://example.invalid/image'),'utf16le');await assert.rejects(check(zip([...valid,['word/_rels/document.xml.rels',bytes]])),e=>e.code==='invalid-document');});
