import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {verify} from '../update-admission.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
async function fixture(){const root=await mkdtemp(join(tmpdir(),'SEP 维护审阅 ')),updatesDirectory=join(root,'updates');await mkdir(updatesDirectory);const key=randomBytes(32);await writeFile(join(updatesDirectory,'control-key'),key);const reportPath=join(root,'report.json');await writeFile(reportPath,JSON.stringify({hardBlocks:[],plugins:[],current:'v1',target:'v2'}));const op={kind:'automatic-sep-only-plan',directory:root,updatesDirectory,reportPath,reportHash:sha(await readFile(reportPath)),graphHashes:{candidate:'a'.repeat(64)}};const opPath=join(root,'operator.json');await writeFile(opPath,JSON.stringify(op));const body={schema:1,kind:'reviewed-profile-graph',id:randomUUID(),directory:root,planPath:join(root,'plan.json'),successor:{id:randomUUID(),hash:'b'.repeat(64)},inputs:[{path:opPath,sha256:sha(await readFile(opPath))},{path:reportPath,sha256:sha(await readFile(reportPath))}]};const plan={...body,hash:sha(JSON.stringify(body))};await writeFile(plan.planPath,JSON.stringify(plan));return {root,key,plan,op,opPath,reportPath}}
test('maintenance confirmation records consent bound to the exact reviewed plan',async()=>{const m=await import('../maintenance-repair.mjs');assert.equal(typeof m.confirmMaintenancePlan,'function');const f=await fixture();const result=await m.confirmMaintenancePlan(f.root,f.plan.hash);assert.equal(result.accepted,true);assert.equal(result.planHash,f.plan.hash);assert.deepEqual(verify(JSON.parse(await readFile(join(f.root,'consent.json'))),f.key),result)});
test('a stale maintenance confirmation cannot write consent',async()=>{const m=await import('../maintenance-repair.mjs');const f=await fixture();await assert.rejects(m.confirmMaintenancePlan(f.root,'c'.repeat(64)),/SEP_PLAN_CONSENT/);await assert.rejects(readFile(join(f.root,'consent.json')),{code:'ENOENT'})});
test('a changed report is rejected even if the user supplies the original plan hash',async()=>{const m=await import('../maintenance-repair.mjs');const f=await fixture();await writeFile(f.reportPath,'{}');await assert.rejects(m.confirmMaintenancePlan(f.root,f.plan.hash),/SEP_REPAIR_INPUT_CHANGED/);await assert.rejects(readFile(join(f.root,'consent.json')),{code:'ENOENT'})});

test('the shipped CLI reviews without consent and rejects a stale confirmation',async()=>{
 const {execFile}=await import('node:child_process'),{promisify}=await import('node:util');const exec=promisify(execFile),f=await fixture();const imports=[];for(let i=0;i<process.execArgv.length;i++){if(process.execArgv[i]==='--import'){imports.push(process.execArgv[i],process.execArgv[++i]);}else if(process.execArgv[i].startsWith('--import='))imports.push(process.execArgv[i]);}
 const cli=new URL('../maintenance-repair.mjs',import.meta.url),{fileURLToPath}=await import('node:url');
 const {stdout}=await exec(process.execPath,[...imports,fileURLToPath(cli),'review',f.root],{windowsHide:true,timeout:15000});assert.equal(JSON.parse(stdout).status,'awaiting-review');await assert.rejects(readFile(join(f.root,'consent.json')),{code:'ENOENT'});
 await assert.rejects(exec(process.execPath,[...imports,fileURLToPath(cli),'confirm',f.root,'d'.repeat(64)],{windowsHide:true,timeout:15000}),e=>e.code===1&&e.stderr.trim()==='SEP_PLAN_CONSENT');await assert.rejects(readFile(join(f.root,'consent.json')),{code:'ENOENT'});
});
