import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rename,unlink,readdir,access} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {pathToFileURL} from 'node:url';
import {Budget} from '../src/budget-ledger.js';
import {acquireBudgetLock} from '../src/budget-lock.js';
import {installP1,p1Config} from '../src/p1.js';
import {openControl} from '../src/p2/control.js';
const exec=promisify(execFile),budgetUrl=new URL('../src/budget-ledger.js',import.meta.url).href;
const missing={code:'BUDGET_LEDGER_MISSING'},usage={prompt_tokens:1,completion_tokens:1};
const scope={kind:'task',taskId:'task:synthetic',rootSessionId:'root',rootTurn:1};
async function fixture(init=true){const directory=await mkdtemp(join(tmpdir(),'sep-ledger-continuity-')),path=join(directory,'budget.json'),budget=new Budget(path,{limit:100});if(init)await budget.init();return {directory,path,budget};}
async function populated(){const f=await fixture();await f.budget.setSessionLimit('root',1,{expectedRevision:0});await f.budget.reserve('before',.8,{scope});await f.budget.settle('before',.7,usage);return f;}
async function removeLedger(f){const retained=join(f.directory,'retained-original.json');await rename(f.path,retained);return retained;}
async function child(script,...args){return exec(process.execPath,['--input-type=module','-e',script,...args],{env:process.env,timeout:20000,windowsHide:true});}
// Catches falsely declaring an unused path lost, or creating state merely by reading it.
test('truly virgin read is side-effect free and the first legitimate write succeeds',async()=>{const f=await fixture(false);assert.equal((await f.budget.snapshot()).accountedCny,0);assert.deepEqual(await readdir(f.directory),[]);await f.budget.init();await f.budget.reserve('first',.1,{scope});assert.equal((await f.budget.snapshot()).accountedCny,.1);});
// Catches the ENOENT-to-empty branch that forgets paid entries and settings.
test('live snapshots and settings reads reject a disappeared initialized ledger',async()=>{const f=await populated(),retained=await removeLedger(f);for(const read of [()=>f.budget.snapshot(),()=>f.budget.sessionSnapshot('root'),()=>f.budget.sessionDefaultsSnapshot(),()=>f.budget.getChildBinding('child')])await assert.rejects(read,missing);await assert.rejects(access(f.path),{code:'ENOENT'});assert.equal(JSON.parse(await readFile(retained)).entries[0].id,'before');});
test('reserve and init do not recreate a missing known ledger',async()=>{const f=await populated();await removeLedger(f);await assert.rejects(f.budget.reserve('after',.1,{scope}),missing);await assert.rejects(f.budget.init(),missing);await assert.rejects(access(f.path),{code:'ENOENT'});});
// A separate process proves persistence rather than relying on an instance boolean.
test('a new process refuses missing ledger while its persistent guard remains',async()=>{const f=await populated();await removeLedger(f);const {stdout}=await child(`import {Budget} from ${JSON.stringify(budgetUrl)};const b=new Budget(process.argv[1],{limit:100});const errors=[];for(const fn of [()=>b.snapshot(),()=>b.init(),()=>b.reserve('new',.1)]){try{await fn();errors.push('accepted')}catch(e){errors.push(e.code)}}console.log(JSON.stringify(errors));`,f.path);assert.deepEqual(JSON.parse(stdout.trim()),['BUDGET_LEDGER_MISSING','BUDGET_LEDGER_MISSING','BUDGET_LEDGER_MISSING']);await assert.rejects(access(f.path),{code:'ENOENT'});});
test('in-process witness remains conservative if ledger and guard are both removed',async()=>{const f=await populated();await removeLedger(f);await unlink(f.path+'.lock.guard.sqlite3');await assert.rejects(f.budget.snapshot(),missing);await assert.rejects(f.budget.init(),missing);});
// Old unmarked formats are legitimate data, not permission to reset their contents.
for(const version of [1,2,3])test(`intact legacy v${version} without coordination metadata preserves existing accounting`,async()=>{const f=await fixture(false),base={version,currency:'CNY',limit:100,initialSpent:.3,entries:[{id:'legacy',status:'reserved',reservedCny:.4,createdAt:'2026-09-27T00:00:00Z'}]};if(version>=2)Object.assign(base,{taskLimits:{},childBindings:{},reconciliations:[],legacyInitialSpent:true});if(version===3)Object.assign(base,{sessionDefault:{limitCny:12,revision:2},sessionLimits:{root:{limitCny:2,revision:4}}});await writeFile(f.path,JSON.stringify(base));await f.budget.init();const now=await f.budget.snapshot();assert.equal(now.accountedCny,.7);assert.equal(now.entries[0].id,'legacy');if(version===3){assert.deepEqual(now.sessionDefault,base.sessionDefault);assert.deepEqual(now.sessionLimits,base.sessionLimits);}});
test('intact ledger can rebuild a missing mutex without losing costs or session policy',async()=>{const f=await populated(),before=JSON.parse(await readFile(f.path));await unlink(f.path+'.lock.guard.sqlite3');await new Budget(f.path,{limit:100}).init();assert.deepEqual(JSON.parse(await readFile(f.path)),before);});
test('malformed mutex refuses writes without replacing an intact ledger',async()=>{const f=await populated(),before=await readFile(f.path);await writeFile(f.path+'.lock.guard.sqlite3','synthetic corrupt sqlite');await assert.rejects(f.budget.reserve('bad',.1),{code:'BUDGET_LOCKED'});assert.deepEqual(await readFile(f.path),before);});
// An acquired/released mutex is an interrupted initialization, not a virgin path.
test('a previous lock-only attempt is not reauthorized as a fresh ledger',async()=>{const f=await fixture(false),lock=await acquireBudgetLock(f.path);await lock.release();await assert.rejects(f.budget.snapshot(),missing);await assert.rejects(f.budget.init(),missing);});
for(const suffix of ['.v2-abc.checkpoint','.previous.tmp','.lock.abandoned-synthetic.json'])test(`prior ${suffix} evidence prevents missing-ledger initialization`,async()=>{const f=await fixture(false);await writeFile(f.path+suffix,'retained synthetic history');await assert.rejects(f.budget.snapshot(),missing);await assert.rejects(f.budget.init(),missing);await assert.rejects(access(f.path),{code:'ENOENT'});});
// A real process death leaves the permanent guard; the OS releases the mutex.
test('crash before first ledger publication stays blocked after process restart',async()=>{const f=await fixture(false);await assert.rejects(child(`import {Budget} from ${JSON.stringify(budgetUrl)};const b=new Budget(process.argv[1],{limit:100});await b.change(()=>process.exit(17));`,f.path),e=>e.code===17);await assert.rejects(new Budget(f.path,{limit:100}).init(),missing);await assert.rejects(access(f.path),{code:'ENOENT'});});
test('crash after publication preserves written accounting when a new owner recovers the lock',async()=>{const f=await fixture(false);await assert.rejects(child(`import {Budget} from ${JSON.stringify(budgetUrl)};const b=new Budget(process.argv[1],{limit:100});await b.change(s=>{s.initialSpent=.2;return {get receipt(){process.exit(17)}}});`,f.path),e=>e.code===17);const reopened=new Budget(f.path,{limit:100});await reopened.init();assert.equal((await reopened.snapshot()).accountedCny,.2);});
test('parallel processes initialize once and retain one shared spending authority',async()=>{const f=await fixture(false);const script=`import {Budget} from ${JSON.stringify(budgetUrl)};const b=new Budget(process.argv[1],{limit:1});try{await b.init();await b.reserve(process.argv[2],.6);console.log('accepted')}catch(e){console.log(e.code)}`;const outcomes=await Promise.all([child(script,f.path,'a'),child(script,f.path,'b')]);assert.deepEqual(outcomes.map(r=>r.stdout.trim()).sort(),['BUDGET_EXCEEDED','accepted']);assert.equal((await new Budget(f.path,{limit:1}).snapshot()).accountedCny,.6);});
test('ledger disappearance during an admitted writer cannot be overwritten by publication',async()=>{const f=await populated(),retained=join(f.directory,'retained-during-write.json');await assert.rejects(f.budget.change(async()=>{await rename(f.path,retained);}),missing);await assert.rejects(access(f.path),{code:'ENOENT'});assert.equal(JSON.parse(await readFile(retained)).entries[0].id,'before');});
// Keeps the actual P1 listener alive when initial budget admission fails.
test('cold P1 budget failure blocks provider and settings while controlled restoration allows retry',async()=>{const f=await populated(),retained=await removeLedger(f),storageRoot=join(f.directory,'storage');await mkdir(storageRoot);const control=await openControl({storageRoot,mode:'writer',initialize:true}),effects=[],listeners=new Map(),agents=new Map(),lifetime=new AbortController();try{const ctx={get:n=>n==='sessions'?{list:()=>[...agents.values()].map(a=>a.session)}:{},agents:{get:id=>agents.get(id)},llm:{},subagents:{getProvider:()=>({})},tools:{guard(){}},effect:fn=>effects.push(fn()),on:(n,fn)=>{const a=listeners.get(n)??[];a.push(fn);listeners.set(n,a);}};const api=await installP1(ctx,{config:p1Config.parse({enabled:true,budgetPath:f.path}),scope:{projects:[]},store:{},signal:lifetime.signal,track:p=>p,runAccess:fn=>control.withAccess(fn)});const agent={id:'root',status:'running',session:{id:'root',header:{id:'root',origin:'user'},snapshotEvents:()=>[]}};agents.set('root',agent);const signal=new AbortController().signal;for(const fn of listeners.get('agent/request'))await fn({agent,turn:2,step:1,signal},async()=>({}));const options={provider:'deepseek-official',model:'deepseek-flash',maxTokens:32,sessionId:'root',signal,messages:[{role:'user',content:[{type:'text',text:'synthetic continuity'}]}],tools:[]};let calls=0;const invoke=async()=>{for await(const chunk of listeners.get('llm/stream')[0](options,async function*(){calls++;yield{type:'usage',usage:{inputTokens:1,cacheReadTokens:0,cacheWriteTokens:0,outputTokens:1}};yield{type:'finish',reason:{kind:'stop'}};})){};};await assert.rejects(invoke(),missing);await assert.rejects(api.budgetSettings.list(),missing);assert.equal(calls,0);await rename(retained,f.path);await invoke();assert.equal(calls,1);const now=await api.budgetSettings.get({sessionId:'root'});assert.equal(now.limitCny,1);assert.ok(now.accountedUpperBoundCny>=.7);assert.ok(JSON.parse(await readFile(f.path)).entries.some(e=>e.id==='before'));}finally{lifetime.abort();await Promise.allSettled(effects.map(fn=>fn()));await control.close();}});