import{readFile,writeFile,mkdir,lstat}from'node:fs/promises';import{join,isAbsolute}from'node:path';import{verifyBundle}from'./integrity.mjs';import{fileHash}from'./operator/shared/sep-update/update-inventory.mjs';import{checkPreparedHealth}from'./operator/shared/sep-update/prepare-health.mjs';import{ensureControlKey}from'./operator/shared/sep-update/prepare-queue.mjs';import{prepareOfflinePlan,assertInstallationIdle,verifySelectedInstallation}from'./operator/offline.mjs';import{privateState}from'./operator/policy.mjs';
const root=import.meta.dirname,json=async p=>JSON.parse(await readFile(p)),save=(p,x)=>writeFile(p,JSON.stringify(x,null,2)+'\n',{flag:'wx'});
/** Prepare health/report/P2 plan only. Approval and publication are separate commands. */
export async function prepareStaged(workRoot){if(!isAbsolute(workRoot??''))throw Error('BRIDGE_ABSOLUTE_PATH_REQUIRED');const bound=await verifyBundle(),stagePath=join(workRoot,'STAGED.json'),stage=await json(stagePath),installation=stage.installation;await assertInstallationIdle(installation,[]);await verifySelectedInstallation(installation);
 for(const p of [join(installation.dailyRoot,'state/budget.json'),join(installation.dailyRoot,'state/budget.json.lock.guard.sqlite3')])try{if(!(await lstat(p)).isFile())throw Error('BRIDGE_LEDGER_NOT_INITIALIZED');}catch(e){if(e.code==='ENOENT')throw Error('BRIDGE_LEDGER_NOT_INITIALIZED');throw e;}
 const privatePath=join(workRoot,'PRIVATE-STATE.json');await save(privatePath,await privateState(installation.home));const witnesses=[];
 for(const p of [join(installation.dailyRoot,'state/budget.json'),join(installation.dailyRoot,'state/budget.json.lock.guard.sqlite3'),installation.credentialsPath])witnesses.push({path:p,sha256:await fileHash(p)});await save(join(workRoot,'PRIVATE-WITNESSES.json'),{schema:1,scope:'Hashes only. Credential and financial values are not copied into reports.',bindings:witnesses});
 for(const direction of ['old','target']){await mkdir(join(workRoot,'temp-'+direction));process.env.TEMP=join(workRoot,'temp-'+direction);process.env.TMP=process.env.TEMP;await checkPreparedHealth({programRoot:direction==='old'?stage.oldRoot:stage.newRoot,probeRoot:join(workRoot,'health-'+direction),graphHash:direction==='old'?stage.oldGraphHash:stage.graphHash,installation,signal:AbortSignal.timeout(300000)});}
 const cdir=join(workRoot,'admission');await mkdir(cdir);const contractPath=join(root,'contracts',stage.label,'exact-changes.json');await writeFile(join(cdir,'exact-changes.json'),await readFile(contractPath),{flag:'wx'});
 const proof={schema:1,kind:'exact-candidate-review-evidence',status:'pass',baseGraphHash:stage.oldGraphHash,targetGraphHash:stage.graphHash,scope:'Authenticated bundle byte bindings and bound empty-profile health. Does not assert all user-plugin runtime compatibility.',bindings:await Promise.all([...bound,stagePath,join(workRoot,'health-old/health.json'),join(workRoot,'health-target/health.json')].map(async path=>({path,sha256:await fileHash(path)})))};const proofPath=join(cdir,'BYTE-AND-HEALTH-BINDINGS.json');await save(proofPath,proof);
 await save(join(cdir,'admission.json'),{...stage.admission,evidenceBindings:{path:proofPath,sha256:await fileHash(proofPath)}});
 const updatesDirectory=join(workRoot,'updates');await ensureControlKey(updatesDirectory);const release={source:'host',version:'0.2.0-rc.2',sepVersion:'0.2.1-beta.2',kind:'fixed-offline-sep-bridge',url:'https://github.com/Lance-QwQ/DSH-SEP/releases/tag/v0.2.1-beta.2'};
 const result=await prepareOfflinePlan({directory:join(workRoot,'review'),installation,prepared:{root:stage.newRoot,baseGraphHash:stage.oldGraphHash,graphHash:stage.graphHash,archive:stagePath,metadata:{stageHash:await fileHash(stagePath),privateStateHash:await fileHash(privatePath)}},healthPath:join(workRoot,'health-target/health.json'),oldHealthPath:join(workRoot,'health-old/health.json'),updatesDirectory,release,hostStagePath:stagePath,privateStatePath:privatePath,admissionPath:join(cdir,'admission.json'),additionalEvidence:witnesses});
 await assertInstallationIdle(installation,[]);await verifySelectedInstallation(installation);for(const row of witnesses)if(await fileHash(row.path)!==row.sha256)throw Error('BRIDGE_PRIVATE_STATE_CHANGED');
 const summary={schema:1,status:'prepared-not-applied',expected:result.expected,operatorPath:join(result.op.directory,'operator.json'),planPath:join(result.op.directory,'plan.json'),reportPath:result.op.reportPath,reportHtmlPath:join(result.op.directory,'report.html'),changedFiles:stage.changedFiles,consentCreated:false,dailySelected:false,counts:{unknown:result.report.plugins.filter(p=>p.verdict==='unknown').length,incompatible:result.report.plugins.filter(p=>p.verdict==='incompatible').length,hardBlocks:result.report.hardBlocks.length}};await save(join(workRoot,'PREPARED.json'),summary);return{...summary,report:result.report};}
