export const zh={
 title:'会话预算',refresh:'刷新',description:'为每个会话窗口设置累计金额安全护栏。默认 100 元，可调整默认值，或为指定会话单独设置。主任务和归属于它的子代理共同计入该会话。',notInvoice:'这是 SEP 的本地估算与预留额度，不是 DeepSeek 账户余额，也不是提供方账单。',
 defaultLimit:'默认单会话上限（元）',defaultHelp:'修改默认值会影响尚未单独设置上限的会话。已产生的消费和预留不会清零。',range:'可设置 0.01 至 1,000,000 元，最多两位小数。',saveDefault:'保存默认上限',session:'会话窗口',noSessions:'尚无可管理的根会话。',sessionLimit:'此会话累计上限（元）',saveSession:'保存此会话上限',usesDefault:'此会话当前使用默认上限。',override:'此会话已使用独立上限，不随默认值变化。',accounted:'累计计入金额',settled:'已结算估算',reserved:'未结预留',remaining:'剩余可用额度',unattributed:'仅计入共享总账的旧／未归属金额',sharedGuard:'共享总预算上限',taskGuard:'单轮任务上限',independent:'三项护栏独立生效。即使将会话上限设为 200 元，请求仍可能被共享总预算剩余额度或单轮上限拦截。设置低于已计入金额后，后续新请求会受限；已发出的请求仍需结算。',retained:'保存只调整护栏。历史消费、子代理归属和未结预留均保留。',unknown:'结果未知的请求仍占用预留；无法归属旧消费只计入共享总账，不猜测分配给某个会话。',confirmed:'上次读取时间',loading:'正在读取已保存的设置…',unavailable:'预算设置暂不可用。',ledgerMissing:'预算账本缺失，已阻止新的模型请求。请恢复并核验原账本，不能清零重建。刷新不会自动重建账本。',ledgerChanged:'预算账本在操作期间发生变化，已拒绝本次写入。请核验原账本并刷新；不会自动重复保存或清零消费。',readError:'读取失败，旧值已隐藏。请刷新后再修改。',unconfirmed:'保存结果未确认，已尝试重新读取。不会自动重复提交；请核对已保存值。',conflict:'设置已被其他操作修改，已重新读取。请核对后再保存。',saved:'设置已保存，正在核对最新值。'
} as const;
export type BudgetLocaleKey=keyof typeof zh;
export const en:Record<BudgetLocaleKey,string>={
 title:'Session budget',refresh:'Refresh',description:'Set a cumulative spending guard for each session window. The default is CNY 100. Override an individual session or change the default. Attributed child agents share the root session guard.',notInvoice:'These are local SEP estimates and reservations, not your DeepSeek account balance or provider invoice.',
 defaultLimit:'Default session limit (CNY)',defaultHelp:'Changing the default affects sessions without an override. Existing usage and reservations are retained.',range:'Enter CNY 0.01–1,000,000, with at most two decimal places.',saveDefault:'Save default limit',session:'Session window',noSessions:'No managed root sessions yet.',sessionLimit:'This session cumulative limit (CNY)',saveSession:'Save session limit',usesDefault:'This session currently uses the default.',override:'This session has an independent limit.',accounted:'Total accounted amount',settled:'Settled estimate',reserved:'Unsettled reservations',remaining:'Remaining allowance',unattributed:'Legacy / unattributed amount in shared ledger only',sharedGuard:'Shared budget limit',taskGuard:'Per-turn task limit',independent:'All three guards apply independently. A CNY 200 session limit can still be blocked by the shared balance or per-turn limit. Lowering a guard below accounted usage blocks new requests; dispatched requests still need settlement.',retained:'Saving only changes the guard. Historical usage, child attribution and unsettled reservations remain intact.',unknown:'Unknown outcomes retain reservations. Legacy unattributed spending stays in the shared ledger and is not guessed into a session.',confirmed:'Last read',loading:'Reading saved settings…',unavailable:'Budget settings unavailable.',ledgerMissing:'The budget ledger is missing. New model requests are blocked. Restore and verify the original ledger; do not reset it to zero. Refresh does not recreate the ledger.',ledgerChanged:'The budget ledger changed during this operation. This write was rejected. Verify the original ledger and refresh; saving will not be retried automatically or reset usage.',readError:'Read failed. Stale values are hidden; refresh before editing.',unconfirmed:'Save outcome is unconfirmed. A readback was attempted without repeating the mutation. Check the saved values.',conflict:'Another operation changed these settings. State was reloaded; review before saving.',saved:'Settings saved; checking the latest values.'
};
