import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,mkdir,writeFile,realpath,symlink,chmod}from'node:fs/promises';import{join}from'node:path';import{tmpdir}from'node:os';import{pathToFileURL}from'node:url';
const pack=process.env.SEP_R8_PACKAGING;
const profile=await import(pathToFileURL(join(pack,'native-install/native-profile.mjs'))).catch(()=>null);
const payload=await import(pathToFileURL(join(pack,'bootstrap/desktop-payload.mjs'))).catch(()=>null);
test('fresh profile has instance-scoped default workspace and activates SEP composition',()=>{assert(profile);const original={config:{p1:{enabled:false},projects:[{root:'@ROOT@/workspace',recoveryProjectId:'@PROJECT_ID@'}]},patch:[{id:'custom',config:{untouched:true}}]};const t=profile.nativeProfile(original);assert.equal(t.patch.find(p=>p.id==='workspace-controller').config.documentsDirectory,'@ROOT@/workspace');const rows=t.patch.flatMap(p=>p.insert??[]);for(const name of ['dsh-sep-brand','dsh-sep-plugin-group'])assert(rows.some(r=>r.name===name));assert.equal(t.config.p1.enabled,true);assert.deepEqual(t.patch[0],original.patch[0]);assert.equal(original.config.p1.enabled,false)});
async function tree(){const root=await realpath(await mkdtemp(join(tmpdir(),'sep-desktop-r8-')));await mkdir(join(root,'actual'));await writeFile(join(root,'actual/bin'),'test executable');await chmod(join(root,'actual/bin'),0o755);await symlink('actual/bin',join(root,'electron'));return root}
test('payload binds executable bytes, native modes and internal relative links',async()=>{assert(payload);const root=await tree(),m={schema:1,platform:process.platform+'-'+process.arch,version:'44.0.0',executable:'electron',...await payload.auditDesktopPayload(root)};await payload.verifyDesktopPayload(root,m);await writeFile(join(root,'actual/bin'),'changed executable');await assert.rejects(()=>payload.verifyDesktopPayload(root,m),/DESKTOP_PAYLOAD_CHANGED/)});
test('manifest rejects an escaping link before installation mutation',()=>{assert(payload);assert.throws(()=>payload.validateDesktopPayload({schema:1,platform:process.platform+'-'+process.arch,version:'44.0.0',executable:'electron',files:[{path:'electron',size:1,mode:0o755,sha256:'a'.repeat(64)}],links:[{path:'escape',target:'../../outside',resolved:'x'}]}),/DESKTOP_PAYLOAD_LINK_ESCAPE/)});
test('manifest rejects duplicate paths and unbound executable',()=>{assert(payload);const base={schema:1,platform:process.platform+'-'+process.arch,version:'44.0.0',executable:'electron',files:[{path:'x',size:1,mode:0o755,sha256:'a'.repeat(64)}],links:[]};assert.throws(()=>payload.validateDesktopPayload(base),/DESKTOP_PAYLOAD_EXECUTABLE/);base.executable='x';base.files.push({...base.files[0]});assert.throws(()=>payload.validateDesktopPayload(base),/DESKTOP_PAYLOAD_DUPLICATE/)});
test('changed link and unexpected files cannot satisfy a receipt',async()=>{assert(payload);const root=await tree(),m={schema:1,platform:process.platform+'-'+process.arch,version:'44.0.0',executable:'electron',...await payload.auditDesktopPayload(root)};await writeFile(join(root,'extra'),'unbound');await assert.rejects(()=>payload.verifyDesktopPayload(root,m),/DESKTOP_PAYLOAD_CHANGED/)});
