import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {installBootstrap} from '../installer.mjs';
const run=promisify(execFile),sha=b=>createHash('sha256').update(b).digest('hex');
async function fixture({brokenEntry=false,brokenDependency=false,missingDependency=false,throws=false}={}){
 const root=await mkdtemp(join(tmpdir(),'SEP 成品入口 ')),bundle=join(root,'bundle'),destination=join(root,'安装 空格');await mkdir(join(bundle,'bootstrap'),{recursive:true});await mkdir(destination);
 const files={'launch.mjs':`import {reportStartupFailure} from './@MANAGED_DIR@/startup-report.mjs';import{join}from'node:path';try{const{run}=await import('./@MANAGED_DIR@/launcher.mjs');await run(join(import.meta.dirname,'@CONFIG_FILE@'));}catch(error){process.exitCode=await reportStartupFailure(import.meta.dirname,error);}`,'launcher.mjs':`import {writeFile} from 'node:fs/promises';export async function run(path){${throws?"throw Error('SYNTHETIC_FAILURE')":"await writeFile(path+'.called',path)"}}`,'startup-report.mjs':`import {writeFile} from 'node:fs/promises';import{join}from'node:path';export async function reportStartupFailure(root,error){await writeFile(join(root,'error.json'),JSON.stringify({root,code:error.message}));return 17}`,'start.ps1':'# synthetic','start.vbs':"' synthetic",'startup-coordinator.mjs':'export {};','startup-diagnostic.mjs':'export {};','startup-lease.mjs':'export {};','credential-reader.mjs':'export {};','checkpoint-inspection.mjs':'export {};'};
 if(brokenEntry)files['launch.mjs']='import {;';if(brokenDependency)files['startup-report.mjs']='export {';if(missingDependency)delete files['startup-report.mjs'];
 const manifest={bootstrap:{schema:1,files:[]},support:[]};for(const[path,body]of Object.entries(files)){const bytes=Buffer.from(body);await writeFile(join(bundle,'bootstrap',path),bytes);const b={path,size:bytes.length,sha256:sha(bytes)};manifest.bootstrap.files.push(b);manifest.support.push({...b,path:'bootstrap/'+path})}
 return{bundle,destination,manifest,graphHash:'a'.repeat(64),nodeExecutable:process.execPath};
}
test('rejects syntax-invalid generated launch bytes before declaring bootstrap installed',async()=>{const f=await fixture({brokenEntry:true});await assert.rejects(installBootstrap(f),/BOOTSTRAP_SYNTAX/);await assert.rejects(readFile(join(f.destination,'managed/bootstrap-receipt.json')),e=>e.code==='ENOENT')});
test('rejects a syntax-invalid required diagnostic module',async()=>{await assert.rejects(installBootstrap(await fixture({brokenDependency:true})),/BOOTSTRAP_SYNTAX/)});
test('rejects missing diagnostic resource before accepting bootstrap',async()=>{await assert.rejects(installBootstrap(await fixture({missingDependency:true})),/BOOTSTRAP_RESOURCE_MISSING/)});
test('executes actual installed entry from a different cwd and Chinese spaced directory',async()=>{const f=await fixture();await installBootstrap(f);await run(process.execPath,[join(f.destination,'launch.mjs')],{cwd:f.bundle,windowsHide:true,timeout:15000});assert.equal(await readFile(join(f.destination,'deployment-rc2.json.called'),'utf8'),join(f.destination,'deployment-rc2.json'))});
test('actual generated error path reports the instance root and preserves the error exit code',async()=>{const f=await fixture({throws:true});await installBootstrap(f);await assert.rejects(run(process.execPath,[join(f.destination,'launch.mjs')],{cwd:f.bundle,windowsHide:true,timeout:15000}),e=>e.code===17);assert.deepEqual(JSON.parse(await readFile(join(f.destination,'error.json'),'utf8')),{root:f.destination,code:'SYNTHETIC_FAILURE'})});
