import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,lstat,realpath,copyFile,chmod} from 'node:fs/promises';
import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {settings,installBootstrap,install} from '../installer.mjs';
const run=promisify(execFile),sha=b=>createHash('sha256').update(b).digest('hex');
async function fixture(){const root=await realpath(await mkdtemp(join(tmpdir(),'SEP 安装准备 '))),bundle=join(root,'bundle'),destination=join(root,'new instance');await mkdir(join(bundle,'bootstrap'),{recursive:true});await mkdir(destination);
 const files={'launch.mjs':"import {run} from './@MANAGED_DIR@/launcher.mjs';await run(import.meta.dirname);",'launcher.mjs':"import{writeFile}from'node:fs/promises';export async function run(p){await writeFile(p+'/called.json',JSON.stringify({cwd:process.cwd(),args:process.argv.slice(2)}));}",'startup-report.mjs':'export {};','startup-coordinator.mjs':'export {};','startup-diagnostic.mjs':'export {};','startup-lease.mjs':'export {};','credential-reader.mjs':'export {};','checkpoint-inspection.mjs':'export {};'};
 if(process.platform==='win32'){files['start.ps1']='# synthetic';files['start.vbs']="' synthetic";}else files['start.sh']=await readFile(new URL('../bootstrap/start.sh',import.meta.url),'utf8');
 const manifest={schema:2,platform:process.platform+'-'+process.arch,bootstrap:{schema:1,files:[]},support:[]};
 for(const[path,body]of Object.entries(files)){const bytes=Buffer.from(body);await writeFile(join(bundle,'bootstrap',path),bytes);const f={path,size:bytes.length,sha256:sha(bytes),mode:path==='start.sh'?0o755:0o644};manifest.bootstrap.files.push(f);manifest.support.push({...f,path:'bootstrap/'+path});}
 return{root,bundle,destination,manifest,graphHash:'a'.repeat(64),nodeExecutable:process.execPath};}
test('settings use native node executable without sharing runtime HOME',()=>{const root=join(tmpdir(),'instance');const c=settings(root,'a');assert.equal(c.nodeExecutable,join(root,'runtime/node',process.platform==='win32'?'node.exe':'bin/node'));assert.equal(c.runtimeUser,join(root,'state/user'));});
test('platform mismatch rejected before create-only destination is created',async()=>{const root=await realpath(await mkdtemp(join(tmpdir(),'sep platform '))),bundle=join(root,'bundle'),destination=join(root,'out');await mkdir(bundle);await writeFile(join(bundle,'manifest.json'),JSON.stringify({schema:2,kind:'full',platform:'unsupported'}));await assert.rejects(install({bundle,destination}),/PACKAGE_PLATFORM/);await assert.rejects(lstat(destination),{code:'ENOENT'});});
test('installs bound native bootstrap; POSIX shell works from different cwd with spaces',{timeout:30000},async()=>{const f=await fixture();await installBootstrap(f);if(process.platform==='win32')return;assert.equal((await lstat(join(f.destination,'start.sh'))).mode&0o777,0o755);await mkdir(join(f.destination,'runtime/node/bin'),{recursive:true});await copyFile(process.execPath,join(f.destination,'runtime/node/bin/node'));await chmod(join(f.destination,'runtime/node/bin/node'),0o755);await run(join(f.destination,'start.sh'),['literal argument'],{cwd:f.bundle,timeout:15000});assert.deepEqual(JSON.parse(await readFile(join(f.destination,'called.json'))),{cwd:f.destination,args:['literal argument']});});
test('rejects bootstrap mode disagreement with support binding',async()=>{const f=await fixture();f.manifest.bootstrap.files[0].mode=0o700;await assert.rejects(installBootstrap(f),/BOOTSTRAP_UNBOUND/);});
