import{readFile,writeFile,mkdir,lstat}from'node:fs/promises';import{join,resolve}from'node:path';import{pathToFileURL}from'node:url';import{createHash}from'node:crypto';import assert from'node:assert/strict';import{buildNativeBundle}from'./native-bundle.mjs';
const[source,previous,program,output]=process.argv.slice(2).map(v=>resolve(v));if(!output)throw Error('USAGE source native-runtime program output');const packaging=join(import.meta.dirname,'packaging'),{install}=await import(pathToFileURL(join(packaging,'installer.mjs'))),template=join(source,'apps/desktop/src/sep-update/runtime/health-template.json');await mkdir(output,{recursive:true});
if(!process.env.SEP_R6_REUSE)for(const kind of ['full','sep']){console.log('bundle '+kind);await buildNativeBundle({program,runtime:join(previous,'runtime'),packaging,template,destination:join(output,'bundle-'+kind),kind})}
const checks=[],check=(name,fn)=>{fn();checks.push({name,status:'pass'})};const a=join(output,'Full A 空白'),b=join(output,'SEP B 空白');if(!process.env.SEP_R6_REUSE){console.log('install full');await install({bundle:join(output,'bundle-full'),destination:a});console.log('install sep');await install({bundle:join(output,'bundle-sep'),destination:b,hostRoot:join(a,'program')});}
const load=p=>import(pathToFileURL(p));const read=async p=>JSON.parse(await readFile(p));const ca=await read(join(a,'deployment-rc2.json')),cb=await read(join(b,'deployment-rc2.json'));check('independent-instance-config',()=>{for(const key of ['home','storageRoot','controlRoot','lockDirectory','runtimeUser','electronUserData'])assert.notEqual(ca[key],cb[key]);assert.notEqual(ca.projects[0].id,cb.projects[0].id)});
for(const c of [ca,cb]){assert.equal((await lstat(join(c.home,'profiles'))).isDirectory(),true);checks.push({name:'profile-directory-ready-'+(c===ca?'a':'b'),status:'pass'});check('native-node-path-'+(c===ca?'a':'b'),()=>assert.equal(c.nodeExecutable,join(c.dailyRoot,'runtime/node/bin/node')));assert.equal((await lstat(join(c.dailyRoot,'start.sh'))).mode&0o777,0o755)}
async function start(c){const {openDaily,loadDeployment}=await load(join(c.dailyRoot,'managed/launcher.mjs')),{startCoordinated}=await load(join(c.dailyRoot,'managed/startup-coordinator.mjs'));const runtime=await startCoordinated(join(c.dailyRoot,'deployment-rc2.json'),{openDaily,loadDeployment});const status=await runtime.client.call('status'),ready=await runtime.client.call('desktopReady'),{openHttpCarrier}=await load(join(c.releaseRoot,'node_modules/@deepseek-ai/dsh-recovery/src/http-carrier.mjs'));const carrier=await openHttpCarrier(ready);return{runtime,pid:status.guardian.pid,ready,carrier,async rpc(method,payload={}){const response=await carrier.fetch(new Request('dsh-app://app/api/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId:'r6',method,payload}),signal:AbortSignal.timeout(15000)}));assert.equal(response.status,200);const r=await response.json();assert.equal(r.result.ok,true,JSON.stringify(r));return r.result.value},async close(){carrier.close();await runtime.close();assert.throws(()=>process.kill(status.guardian.pid,0),{code:'ESRCH'})}}}
let first,second;try{first=await start(ca);second=await start(cb);check('concurrent-owned-hosts',()=>{assert.notEqual(first.pid,second.pid);assert.notEqual(new URL(first.ready.url).port,new URL(second.ready.url).port)});const beforeA=await first.rpc('sep-budget/list'),beforeB=await second.rpc('sep-budget/list');check('both-budget-services-ready',()=>{assert.equal(beforeA.available,true);assert.equal(beforeB.available,true)});await first.rpc('sep-budget/updateDefault',{limitCny:80,expectedRevision:beforeA.defaults.revision});const afterB=await second.rpc('sep-budget/list');check('other-instance-remains-100',()=>assert.equal(afterB.defaults.limitCny,100));const memories=await first.rpc('sep-memory/list'),state=await first.rpc('sep-memory/get',{projectId:memories.projects[0].id});await first.rpc('sep-memory/update',{projectId:state.projectId,expected:state.controls,controls:{capture:false,recall:false}});await first.close();first=null;const still=await second.rpc('sep-budget/list');check('second-survives-first-shutdown',()=>assert.equal(still.available,true));}
finally{if(first)await first.close();if(second)await second.close()}
const {Budget}=await load(join(ca.releaseRoot,'node_modules/dsh-system-enhancement-package/src/budget-ledger.js'));const budget=new Budget(join(a,'state/budget.json'),{limit:100});await budget.reserve('r6-synthetic-receipt',2);await budget.settle('r6-synthetic-receipt',1.25,{prompt_tokens:10,completion_tokens:10});await mkdir(join(a,'home/user-plugins'),{recursive:true});await writeFile(join(a,'home/user-plugins/keep.txt'),'r6 synthetic user-installed plugin marker\n');
let restarted;try{restarted=await start(ca);const v=await restarted.rpc('sep-budget/list');check('installed-restart-settings',()=>assert.equal(v.defaults.limitCny,80));check('nonzero-ledger-survives-restart',()=>assert.equal(v.shared.accountedUpperBoundCny,1.25));}finally{if(restarted)await restarted.close()}
const invalid=join(output,'unsupported-host');await mkdir(join(invalid,'node_modules/@deepseek-ai/dsh'),{recursive:true});await writeFile(join(invalid,'node_modules/@deepseek-ai/dsh/package.json'),JSON.stringify({version:'0.0.0'}));const refused=join(output,'must-not-exist');await assert.rejects(()=>install({bundle:join(output,'bundle-sep'),destination:refused,hostRoot:invalid}),/HOST_VERSION_UNSUPPORTED/);await assert.rejects(lstat(refused),{code:'ENOENT'});checks.push({name:'unsupported-host-refused-before-write',status:'pass'});
const result={schema:1,status:'pass',platform:process.platform,arch:process.arch,checks,installations:[a,b],graphHash:ca.graphHash,scope:'Real installer, full and SEP-only using exact already-adapted host input, concurrent SEP instances, nonzero synthetic ledger, controlled shutdown. No official unmodified host coexistence, GUI or update transaction yet.'};await writeFile(join(output,'INSTALL-RESULT.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));