import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {once} from 'node:events';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {randomUUID} from 'node:crypto';
import {load,modules,plugin,evidence,sourceBinding,stage} from './host.mjs';
const {createUserMessage,resolveImageAttachmentAccess}=await load('dsh-llm'),{SessionId}=await load('dsh-session'),{DeepSeekAdapter,resolveAdapterOptions}=await load('dsh-llm-deepseek'),{Budget}=await import(pathToFileURL(join(stage,'src/budget-ledger.js')));
const sse=events=>events.map(event=>`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`).join('');
function response(n,{tool,args={},callId='tool-'+n}={}){return sse([{type:'message_start',message:{id:'synthetic-'+n,type:'message',role:'assistant',model:'deepseek-flash',usage:{input_tokens:100,cache_read_input_tokens:9000,cache_creation_input_tokens:0,output_tokens:0}}},...(tool?[{type:'content_block_start',index:0,content_block:{type:'tool_use',id:callId,name:tool,input:{}}},{type:'content_block_delta',index:0,delta:{type:'input_json_delta',partial_json:JSON.stringify(args)}}]:[{type:'content_block_start',index:0,content_block:{type:'text',text:''}},{type:'content_block_delta',index:0,delta:{type:'text_delta',text:'SYNTHETIC_DONE'}}]),{type:'content_block_stop',index:0},{type:'message_delta',delta:{stop_reason:tool?'tool_use':'end_turn'},usage:{output_tokens:10}},{type:'message_stop'}]);}
async function setup(t,name,{scenario='echo',taskLimitCny=5}={}){
 const dir=join(evidence,name);await mkdir(dir);const workspace=join(dir,'workspace');await mkdir(workspace);const budgetPath=join(dir,'budget.json');
 const readLedger=async()=>JSON.parse(await readFile(budgetPath,'utf8')),events=[],requests=[],errors=[],wire=[],transport=[],faults=[],children=[];let ctx,agent;
 const server=createServer((req,res)=>{void(async()=>{assert.equal(req.url,'/anthropic/v1/messages');const chunks=[];for await(const part of req)chunks.push(part);const body=JSON.parse(Buffer.concat(chunks).toString());const ledger=await readLedger();assert.ok(ledger.entries.some(e=>e.status==='reserved'&&e.phase==='dispatched'),'real P1 persists dispatch before provider HTTP');wire.push(body);transport.push({path:req.url,request:requests.at(-1),reserved:ledger.entries.filter(e=>e.status==='reserved').map(e=>({id:e.id,taskId:e.taskId,phase:e.phase}))});
  if(scenario==='http-error'){res.writeHead(500,{'content-type':'application/json'});res.end('{"error":{"type":"api_error","message":"Synthetic unknown provider outcome"}}');return;}
  let tool,args;if(wire.length===1){if(scenario==='echo')tool='suite_fixture_echo';if(scenario==='delegate'){tool='suite_delegate';args={tasks:[{label:'bound-child',prompt:'Return SYNTHETIC_DONE. Do not call tools.'}]};}if(scenario==='task-cap')tool='suite_fixture_prior_charge';}
  if(scenario==='status-repeat'&&(wire.length===1||wire.length===3))tool='suite_status';
  res.writeHead(200,{'content-type':'text/event-stream'});res.end(response(wire.length,{tool,args,...scenario==='status-repeat'?{callId:'reused-status-call'}:{}}));
 })().catch(error=>{errors.push({stage:'http-fixture',code:error.code,message:error.message});res.destroy(error);});});server.listen(0,'127.0.0.1');await once(server,'listening');
 const {Context}=await load('cordis');ctx=new Context();
 t.after(async()=>{try{await ctx.fiber.dispose();}finally{const closed=new Promise((resolve,reject)=>server.close(error=>error?reject(error):resolve()));server.closeAllConnections();await closed;}await writeFile(join(dir,'observed.json'),JSON.stringify({sourceBinding,scenario,events,requests,errors,wire,transport,faults,children,agentStatus:agent?.status,serverListening:server.listening},null,2)+'\n');
  const reader=new Context();try{const backend=await load('dsh-session-persistence-jsonl');await reader.plugin(backend.default,{root:join(dir,'sessions')});for(const id of new Set(events.map(row=>row.sessionId))){const handle=await reader.sessionPersistence.open(SessionId(id),'read');try{const durable=await handle.read();const observed=events.filter(row=>row.sessionId===id).map(row=>row.event);const prefix=durable.events.filter(event=>event.seq<observed[0].seq);if(id===agent.id)assert.equal(prefix.length,0);else{assert.equal(prefix.length,1);assert.equal(prefix[0].type,'approval/policy');assert.equal(prefix[0].seq,0);assert.deepEqual(prefix[0].data,{policy:'never',source:'delegation'});}assert.deepEqual(durable.events.slice(prefix.length),observed);await writeFile(join(dir,'durable-'+id+'.json'),JSON.stringify(durable,null,2)+'\n');}finally{await handle.close();}}}finally{await reader.fiber.dispose();}
 });
 const map=new Map(modules),connection=resolveAdapterOptions({baseURL:`http://127.0.0.1:${server.address().port}/anthropic`,maxTokens:128,reasoningEffort:'off',streamIdleTimeoutMs:3000,filesApiTimeoutMs:3000,retryPolicy:{mode:'normal',maxRetries:0}});
 map.set('recorded-deepseek-endpoint',{name:'recorded-deepseek-endpoint',inject:['llm','attachments','fs'],apply(c){const adapter=new DeepSeekAdapter({options:()=>connection,resolveAuth:async()=>({headers:{}}),resolveUserId:()=> 'synthetic-budget-test',resolveAttachments:()=>c.get('attachments'),resolveImageAccess:(attachments,ref)=>resolveImageAttachmentAccess(attachments,p=>c.get('fs').processPathFromHostPath(p),ref),prepareExtensions:async()=>({fields:{},accept:async()=>{}})});c.llm.registerAdapter(['deepseek-official'],adapter);}});map.set('sep-under-test',plugin);
 map.set('budget-fixture-tools',{name:'budget-fixture-tools',inject:['tools'],apply(c){
  c.tools.register({name:'suite_fixture_echo',description:'Synthetic isolated no-op',parameters:{type:'object',properties:{}},output:{schema:{type:'object'},render:(_a,v)=>[{type:'text',text:JSON.stringify(v)}]},async execute(){return {ok:true};}});
  c.tools.register({name:'suite_fixture_prior_charge',description:'Synthetic persisted prior charge to exercise one task cap',parameters:{type:'object',properties:{}},output:{schema:{type:'object'},render:(_a,v)=>[{type:'text',text:JSON.stringify(v)}]},async execute(_args,exec){const ledger=await readLedger(),current=ledger.entries.findLast(e=>e.scope?.rootSessionId===exec.agent.id&&e.status==='settled');assert.ok(current);const b=new Budget(budgetPath,{limit:1,taskLimitCny}),id='fixture-prior-'+randomUUID();const amount=taskLimitCny-0.005;await b.reserve(id,amount,{model:'deepseek-flash',scope:current.scope});await b.markDispatched(id);await b.settle(id,amount,{prompt_tokens:0,completion_tokens:0});faults.push({kind:'synthetic-prior-task-charge',entryId:id,amount,taskId:current.taskId,scope:'Test-only ledger API injection, not provider invoice evidence'});return {priorChargePrepared:true};}});
 }});
 const names=['dsh-llm','dsh-session','dsh-session-projection','dsh-system-prompt','dsh-tools','dsh-agent','dsh-agent-loop','dsh-fs-local','dsh-fs-observation-policy','dsh-tool-fs','dsh-attachment-local','dsh-storage','dsh-storage-json','dsh-storage-domain','dsh-subagent','dsh-subagent-spawn-in-process','dsh-user-approval','dsh-session-persistence-jsonl','recorded-deepseek-endpoint','sep-under-test','budget-fixture-tools'];
 const config={'dsh-tools':{mode:'native'},'dsh-agent-loop':{agents:[]},'dsh-fs-local':{cwd:workspace},'dsh-attachment-local':{dshHome:join(dir,'home')},'dsh-storage-json':{root:join(dir,'storage')},'dsh-storage-domain':{backend:'json'},'dsh-session-persistence-jsonl':{root:join(dir,'sessions')},'sep-under-test':{enabled:true,lockDirectory:join(dir,'locks'),projects:[{root:workspace,sources:['.']}],modules:{rag:false,memory:false,media:false},p1:{enabled:true,model:'deepseek-flash',maxTokens:128,budgetPath,limitCny:1,taskLimitCny,profileLimits:{maxInputBytes:250000,maxOutputTokens:128}}}};
 await writeFile(join(dir,'cordis.yml'),JSON.stringify(names.map(name=>({name,...config[name]?{config:config[name]}:{}})),null,2)+'\n');const loader=await load('cordis-plugin-loader'),include=await load('cordis-plugin-include');ctx.baseUrl=pathToFileURL(dir).href+'/';await ctx.plugin(loader.default);ctx.loader.builtins.include=include.default;ctx.loader.internal={version:'v2',async import(name){assert.ok(map.has(name));return map.get(name);}};await ctx.loader.create({name:'cordis:include',config:{path:pathToFileURL(join(dir,'cordis.yml')).href}});await ctx.loader.await();assert.ok(ctx.get('suiteEnhancements'));assert.ok(ctx.tools.get('suite_delegate'));
 ctx.on('session/event',(session,event)=>events.push({sessionId:session.id,event}));ctx.on('agent/error',payload=>errors.push({stage:'agent',code:payload.error?.code,message:payload.error?.message}));ctx.on('subagent/start',info=>children.push({id:info.id,parentId:info.parentId}));ctx.on('llm/stream',async function*(options,next){requests.push({sessionId:options.sessionId,model:options.model,maxTokens:options.maxTokens,purpose:options.purpose});yield*next();});
 agent=await ctx.agentLoop.create(SessionId(name),{provider:'deepseek-official',model:'deepseek-flash',maxTokens:128},{cwd:workspace});
 const rootEvents=()=>events.filter(row=>row.sessionId===agent.id).map(row=>row.event);
 async function send(text){const prior=rootEvents().filter(e=>e.type==='turn/start').length;agent.followup(createUserMessage({content:[{type:'text',text}],source:{kind:'user'}}));await agent.whenIdle();assert.equal(rootEvents().filter(e=>e.type==='turn/start').length,prior+1);return rootEvents().filter(e=>e.type==='turn/end').at(-1);}
 return {ctx,agent,dir,budgetPath,readLedger,send,wire,requests,events,errors,children,faults,rootEvents};
}
test('real Loader and AgentLoop reuse one task for two steps, then allocate a new task for the next turn',{timeout:30000},async t=>{const r=await setup(t,'task-turns');assert.equal((await r.send('Call suite_fixture_echo, then finish.')).data.reason.kind,'completed');assert.equal((await r.send('Begin the next independent task.')).data.reason.kind,'completed');const ledger=await r.readLedger();assert.equal(r.wire.length,3);assert.equal(ledger.entries.length,3);const [a,b,c]=ledger.entries;assert.equal(a.scope.kind,'task');assert.equal(a.scope.rootTurn,1);assert.equal(a.taskId,b.taskId);assert.notEqual(a.taskId,c.taskId);assert.equal(c.scope.rootTurn,2);for(const e of ledger.entries){assert.equal(e.status,'settled');assert.equal(e.chargeCeilingCny,0.00064);assert.deepEqual(e.accounting.usageDetail,{inputTokens:100,cacheReadTokens:9000,cacheWriteTokens:0,outputTokens:10});}assert.equal(r.agent.status,'idle');});
test('suite_delegate creates a real native child with the same durable parent task budget',{timeout:30000},async t=>{const r=await setup(t,'task-child',{scenario:'delegate'});const end=await r.send('Delegate one read-only answer, then finish.');assert.equal(end.data.reason.kind,'completed',JSON.stringify(end));assert.equal(r.wire.length,3);const ledger=await r.readLedger();assert.equal(ledger.entries.length,3);assert.equal(new Set(ledger.entries.map(e=>e.taskId)).size,1);assert.equal(r.children.length,1);assert.deepEqual(ledger.childBindings[r.children[0].id],ledger.entries[0].scope);const childRequest=r.requests.find(q=>q.sessionId!==r.agent.id);assert.ok(childRequest);assert.equal(childRequest.sessionId,r.children[0].id);assert.ok(ledger.entries.every(e=>e.status==='settled'));});
test('persisted charge reaches only one real task cap while a new turn still dispatches',{timeout:30000},async t=>{const r=await setup(t,'task-cap',{scenario:'task-cap',taskLimitCny:0.1});const first=await r.send('Run suite_fixture_prior_charge then try to continue.');assert.notEqual(first.data.reason.kind,'completed');assert.ok(r.errors.some(e=>e.code==='TASK_BUDGET_EXCEEDED'),JSON.stringify(r.errors));assert.equal(r.wire.length,1,'refused second step must not reach HTTP');const old=(await r.readLedger()).entries[0].taskId;assert.equal(r.faults.length,1);const second=await r.send('Start a fresh task and answer directly.');assert.equal(second.data.reason.kind,'completed',JSON.stringify(second));assert.equal(r.wire.length,2);const last=(await r.readLedger()).entries.at(-1);assert.notEqual(last.taskId,old);assert.equal(last.scope.rootTurn,2);assert.equal(last.status,'settled');});
test('real Agent cancellation after durable reserve but before dispatch releases prepared budget',{timeout:30000},async t=>{const r=await setup(t,'cancel-prepared',{scenario:'plain'}),original=Budget.prototype.reserve;let injected=0;Budget.prototype.reserve=async function(...args){const row=await original.apply(this,args);if(this.path===r.budgetPath){injected++;r.faults.push({kind:'cancel-after-reserve-before-dispatch',method:'real Agent.cancel',entryId:row.id});r.agent.cancel({kind:'user'});}return row;};try{const end=await r.send('This is cancelled at the prepared boundary.');assert.notEqual(end.data.reason.kind,'completed');}finally{Budget.prototype.reserve=original;}assert.equal(injected,1);assert.equal(r.wire.length,0);const [e]=(await r.readLedger()).entries;assert.equal(e.status,'released');assert.equal(e.phase,'prepared');assert.equal(e.releaseReason,'cancelled-before-dispatch');assert.equal(r.agent.status,'idle');});
test('real HTTP failure after dispatch keeps one unknown reservation and finishes without retry',{timeout:30000},async t=>{const r=await setup(t,'provider-unknown',{scenario:'http-error'});const end=await r.send('Receive one synthetic transport failure.');assert.notEqual(end.data.reason.kind,'completed');assert.equal(r.wire.length,1);const ledger=await r.readLedger();assert.equal(ledger.entries.length,1);assert.equal(ledger.entries[0].status,'reserved');assert.equal(ledger.entries[0].phase,'unknown');assert.ok(ledger.entries[0].reservedCny>0&&ledger.entries[0].reservedCny<1);assert.equal(r.agent.status,'idle');});

test('real suite_status resolves the current task across repeated provider call IDs in two native turns',{timeout:30000},async t=>{const r=await setup(t,'status-repeat',{scenario:'status-repeat',taskLimitCny:0.5});for(let turn=1;turn<=2;turn++){assert.equal((await r.send('Call suite_status, then finish turn '+turn+'.')).data.reason.kind,'completed');const result=r.rootEvents().filter(e=>e.type==='tool/result'&&e.data.turn===turn).at(-1);assert.ok(result);assert.equal(result.data.message.isError,false);assert.equal(result.data.message.toolCallId,'reused-status-call');const value=JSON.parse(result.data.message.content.filter(b=>b.type==='text').map(b=>b.text).join(''));assert.equal(value.p1.budget.taskLimitCny,0.5,'real tool execution must keep task scope rather than become background');assert.equal(value.p1.budget.taskAccountedCny,0.00064,'suite_status must resolve this turn task, not reuse the prior turn with the same provider call ID');}const ledger=await r.readLedger();assert.equal(r.wire.length,4);assert.equal(ledger.entries.length,4);const[a,b,c,d]=ledger.entries;assert.equal(a.taskId,b.taskId);assert.equal(c.taskId,d.taskId);assert.notEqual(a.taskId,c.taskId);assert.equal(a.scope.rootTurn,1);assert.equal(c.scope.rootTurn,2);});
