import assert from 'node:assert/strict';
import {readFile,realpath,lstat,mkdir,mkdtemp,cp,symlink,writeFile} from 'node:fs/promises';
import {join,resolve,isAbsolute} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const lockPath=process.env.SEP_WORKFLOW_HOST_LOCK?process.env.SEP_WORKFLOW_HOST_LOCK:fileURLToPath(new URL('./host-lock.json',import.meta.url));
assert.ok(isAbsolute(lockPath),'The Host lock must be explicit and absolute');
const pathKey=path=>process.platform==='win32'?path.toLowerCase():path;
assert.equal((await lstat(lockPath)).isSymbolicLink(),false);assert.equal(pathKey(await realpath(lockPath)),pathKey(resolve(lockPath)));
const lockBytes=await readFile(lockPath),lock=JSON.parse(lockBytes);
assert.ok(['win32','linux','darwin'].includes(process.platform));assert.equal(process.platform,lock.platform,'Use a reviewed lock for this platform');assert.equal(process.arch,lock.arch);
assert.equal(Number(process.versions.node.split('.')[0]),lock.nodeMajor);
assert.ok(process.env.SEP_WORKFLOW_HOST,'SEP_WORKFLOW_HOST is required; no daily-install fallback');
assert.ok(process.env.SEP_WORKFLOW_EVIDENCE_ROOT,'SEP_WORKFLOW_EVIDENCE_ROOT is required');
assert.ok(isAbsolute(process.env.SEP_WORKFLOW_HOST),'The Host root must be absolute');assert.ok(isAbsolute(process.env.SEP_WORKFLOW_EVIDENCE_ROOT),'The evidence root must be absolute');
export const root=resolve(process.env.SEP_WORKFLOW_HOST);
assert.equal((await lstat(root)).isSymbolicLink(),false);assert.equal(pathKey(await realpath(root)),pathKey(root));
const evidenceRoot=resolve(process.env.SEP_WORKFLOW_EVIDENCE_ROOT);
await mkdir(evidenceRoot,{recursive:true});assert.equal((await lstat(evidenceRoot)).isSymbolicLink(),false);assert.equal(pathKey(await realpath(evidenceRoot)),pathKey(evidenceRoot));
export const hash=value=>createHash('sha256').update(value).digest('hex');
const graphBytes=await readFile(join(root,'graph.json'));assert.equal(hash(graphBytes),lock.graphSha256,'The explicit Host graph differs from the pinned test host');
export const graph=JSON.parse(graphBytes),ids=new Set(),modules=new Map();
function collect(id){assert.ok(id);if(ids.has(id))return;ids.add(id);const pkg=graph.packages.find(p=>p.id===id);assert.ok(pkg);for(const dependency of Object.values(pkg.dependencies??{}))collect(dependency);}
for(const name of lock.entries)collect(graph.roots[name]);
const files=graph.files.filter(file=>ids.has(file.path.split('/')[1]));let cursor=0;
await Promise.all(Array.from({length:4},async()=>{while(cursor<files.length){const file=files[cursor++],path=join(root,file.path);assert.equal(pathKey(await realpath(path)),pathKey(path));assert.equal(hash(await readFile(path)),file.sha256,'Host file differs: '+file.path);}}));
for(const pkg of graph.packages.filter(p=>ids.has(p.id)))for(const [name,id] of Object.entries(pkg.dependencies??{}))assert.equal(pathKey(await realpath(join(root,'store',pkg.id,'node_modules',name))),pathKey(join(root,'store',id)),'Host dependency redirected');
export const load=name=>import(pathToFileURL(join(root,'store',graph.roots['@deepseek-ai/'+name],'lib/index.js')));
for(const name of lock.entries.filter(name=>name.startsWith('@deepseek-ai/')&&name!=='@deepseek-ai/dsh-recovery')){const module=await load(name.slice('@deepseek-ai/'.length));modules.set(name.slice('@deepseek-ai/'.length),module.default??module);}
export const recovery=await import(pathToFileURL(join(root,'store',graph.roots['@deepseek-ai/dsh-recovery'],'src/index.mjs')));
export const recoveryPlugin=await import(pathToFileURL(join(root,'store',graph.roots['@deepseek-ai/dsh-recovery'],'src/host-plugin.mjs')));
await mkdir(evidenceRoot,{recursive:true});export const evidence=await mkdtemp(join(evidenceRoot,'run-'));
export const stage=join(evidence,'suite-stage'),source=process.env.SEP_WORKFLOW_SOURCE?resolve(process.env.SEP_WORKFLOW_SOURCE):fileURLToPath(new URL('../../src',import.meta.url));
assert.ok(isAbsolute(source));assert.equal((await lstat(source)).isSymbolicLink(),false);await mkdir(stage);await cp(source,join(stage,'src'),{recursive:true,errorOnExist:true,force:false});await writeFile(join(stage,'package.json'),'{"type":"module"}\n');
await symlink(join(root,'store',graph.roots['dsh-system-enhancement-package'],'node_modules'),join(stage,'node_modules'),process.platform==='win32'?'junction':'dir');
export const suite=await import(pathToFileURL(join(stage,'src/index.js'))),plugin=await import(pathToFileURL(join(stage,'src/sep-safe-change/index.js')));
const sourceFiles=['index.js','scope.js','errors.js','recovery-binding.js','session-events.js','sep-safe-change/index.js','sep-safe-change/confirmation.js','sep-safe-change/safe-change.js','sep-safe-change/validation.js','sep-safe-change/closeout.js'];
export const sourceBinding={platform:process.platform,arch:process.arch,hostLockPath:lockPath,hostLockSha256:hash(lockBytes),hostVersion:lock.hostVersion,hostGraphSha256:hash(graphBytes),verifiedHostFiles:files.length,nodeVersion:process.version,source,sourceHashes:Object.fromEntries(await Promise.all(sourceFiles.map(async file=>[file,hash(await readFile(join(stage,'src',file)))])))};
await writeFile(join(evidence,'source-binding.json'),JSON.stringify(sourceBinding,null,2)+'\n');console.log('Isolated workflow evidence:',evidence);
