import {readFile,writeFile} from 'node:fs/promises';import{join,resolve}from'node:path';import{pathToFileURL}from'node:url';import assert from'node:assert/strict';
const[source,root,program,probeName='probe-native']=process.argv.slice(2).map((v,i)=>i<3?resolve(v):v);if(!source||!root||!program)throw Error('USAGE source output program [probe]');
const load=p=>import(pathToFileURL(p));const {checkPreparedHealth}=await load(join(source,'apps/desktop/src/sep-update/prepare-health.mjs'));const report=JSON.parse(await readFile(join(program,'assembly-report.json')));const probe=join(root,probeName);
const baseline=await checkPreparedHealth({programRoot:program,probeRoot:probe,graphHash:report.graphHash,installation:{dailyRoot:root,nodeExecutable:join(root,'runtime/primary-runtime/dependencies/node/bin',process.platform==='win32'?'node.exe':'node'),pnpmEntry:join(root,'runtime/primary-runtime/dependencies/pnpm/bin/pnpm.cjs')},signal:AbortSignal.timeout(180000)});console.log('baseline-health pass');
const configPath=join(probe,'managed/suite-config.json'),config=JSON.parse(await readFile(configPath));config.p1.enabled=true;await writeFile(configPath,JSON.stringify(config,null,2));
const patchPath=join(probe,'program-profile/cordis.patch.yml'),patch=JSON.parse(await readFile(patchPath));patch.push({insert:[{id:'sep-plugin-group',name:'dsh-sep-plugin-group',config:{enabled:true,projects:[{id:config.projects[0].recoveryProjectId,root:config.projects[0].root}]}},{id:'sep-brand',name:'dsh-sep-brand',config:{}}]});await writeFile(patchPath,JSON.stringify(patch,null,2));
const {openDaily,loadDeployment}=await load(join(probe,'launcher/launcher.mjs')),{startCoordinated}=await load(join(probe,'launcher/startup-coordinator.mjs')),{openHttpCarrier}=await load(join(program,'node_modules/@deepseek-ai/dsh-recovery/src/http-carrier.mjs'));
const checks=[];const check=(name,fn)=>{fn();checks.push({name,status:'pass'})};let saved,projectId,controls;
for(let round=1;round<=2;round++){let runtime,carrier,pid;try{runtime=await startCoordinated(join(probe,'deployment-rc2.json'),{openDaily,loadDeployment});const status=await runtime.client.call('status');pid=status.guardian.pid;check('round-'+round+'-host-open',()=>assert.equal(status.writerState,'open'));carrier=await openHttpCarrier(await runtime.client.call('desktopReady'));
async function rpc(method,payload={},expect=true){const response=await carrier.fetch(new Request('dsh-app://app/api/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId:'r5-'+round,method,payload}),signal:AbortSignal.timeout(15000)}));assert.equal(response.status,200);const reply=await response.json();if(expect)assert.equal(reply.result.ok,true,JSON.stringify(reply));return expect?reply.result.value:reply.result;}
const memory=await rpc('sep-memory/list');check('round-'+round+'-memory-available',()=>{assert.equal(memory.available,true);assert.equal(memory.projects.length,1)});projectId=memory.projects[0].id;const memoryState=await rpc('sep-memory/get',{projectId});const budget=await rpc('sep-budget/list');console.log('budget-view',JSON.stringify(budget));check('round-'+round+'-budget-available',()=>{assert.equal(budget.available,true);assert.equal(budget.taskLimitCny,5);assert.equal(budget.shared.limitCny,100)});
if(round===1){check('default-limit-100',()=>assert.equal(budget.defaults.limitCny,100));const invalid=await rpc('sep-budget/updateDefault',{limitCny:-1,expectedRevision:budget.defaults.revision},false);check('invalid-limit-rejected',()=>assert.equal(invalid.ok,false));saved=await rpc('sep-budget/updateDefault',{limitCny:80,expectedRevision:budget.defaults.revision});const conflict=await rpc('sep-budget/updateDefault',{limitCny:90,expectedRevision:budget.defaults.revision},false);check('stale-revision-rejected',()=>assert.equal(conflict.error.message,'BUDGET_SETTINGS_CONFLICT'));controls={capture:!memoryState.controls.capture,recall:!memoryState.controls.recall};await rpc('sep-memory/update',{projectId,expected:memoryState.controls,controls});}
else{check('limit-survives-restart',()=>assert.equal(budget.defaults.limitCny,80));check('revision-survives-restart',()=>assert.equal(budget.defaults.revision,saved.revision));check('memory-controls-survive-restart',()=>assert.deepEqual(memoryState.controls,controls));check('no-model-consumption',()=>assert.equal(budget.shared.accountedUpperBoundCny,0));}
const idle=await runtime.client.call('desktopQuitInspection');check('round-'+round+'-idle',()=>{assert.equal(idle.activeTasks,false);assert.equal(idle.scheduledTasks,false)});
}finally{carrier?.close();if(runtime)await runtime.close();}check('round-'+round+'-owned-process-exited',()=>assert.throws(()=>process.kill(pid,0),{code:'ESRCH'}));}
const result={schema:1,status:'pass',platform:process.platform,arch:process.arch,graphHash:report.graphHash,baseline,checks,scope:'Native managed desktop-host, recovery, P2 empty store, P1 enabled, memory/budget settings, plugin-group and brand mounted. Two restarts. No model calls, interactive Electron, full plugin feature coverage or update transaction.'};await writeFile(join(root,'HEALTH-RESULT.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));