import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{join}from'node:path';
import{assertAdmission,verifyExactGraph}from'../operator/exact-contract.mjs';
const root=join(import.meta.dirname,'../contracts'),pairs=JSON.parse(await readFile(join(root,'PAIRS.json'))),json=async p=>JSON.parse(await readFile(p));
for(const pair of pairs){const before=await json(join(root,pair.label,'before-graph.json')),after=await json(join(root,pair.label,'after-graph.json')),contract=await json(join(root,pair.label,'exact-changes.json'));const admission={schema:1,kind:'exact-same-host-adaptation-input',hostVersion:'0.2.0-rc.2',fromSepVersion:'0.2.1-beta.1',sepVersion:'0.2.1-beta.2',...pair};
test(pair.label+': accepts the reviewed Beta.2 identity and exact delta',()=>{assert.equal(assertAdmission(admission).targetGraphHash,'96fbacddd11ac56871f1909e1a9f00ccd3669a5a365e8d7061cb8f5cd7ac7143');assert.equal(verifyExactGraph(before,after,contract).changedFiles,pair.label==='public-beta1'?28:7);});
test(pair.label+': rejects unlisted code changes',()=>{const changed=structuredClone(after);const f=changed.files.find(x=>x.path.includes('/lib/')&&!contract.changes.some(y=>y.path===x.path));f.sha256='0'.repeat(64);assert.throws(()=>verifyExactGraph(before,changed,contract),e=>e.code==='EXACT_UNLISTED_FILE');});
test(pair.label+': rejects a forged payload binding',()=>{const changed=structuredClone(contract);changed.changes[0].after.sha256='0'.repeat(64);assert.throws(()=>verifyExactGraph(before,after,changed),e=>e.code==='EXACT_FILE_BINDING');});
test(pair.label+': rejects removing a reviewed file',()=>{const changed=structuredClone(after);changed.files=changed.files.filter(x=>x.path!==contract.changes[0].path);assert.throws(()=>verifyExactGraph(before,changed,contract));});
}
test('rejects unknown graph despite claiming the same version',()=>{const a={schema:1,kind:'exact-same-host-adaptation-input',hostVersion:'0.2.0-rc.2',fromSepVersion:'0.2.1-beta.1',sepVersion:'0.2.1-beta.2',baseGraphHash:'1'.repeat(64),targetGraphHash:pairs[0].targetGraphHash,contractSha256:pairs[0].contractSha256};assert.throws(()=>assertAdmission(a));});
test('rejects changing the contract itself',()=>{const a={schema:1,kind:'exact-same-host-adaptation-input',hostVersion:'0.2.0-rc.2',fromSepVersion:'0.2.1-beta.1',sepVersion:'0.2.1-beta.2',...pairs[0],contractSha256:'2'.repeat(64)};assert.throws(()=>assertAdmission(a));});
