import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile,copyFile,symlink} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {verifyExactGraph,verifyInventoryPreservation,digest} from '../operator/exact-contract.mjs';
import {validatePlanConsent} from '../operator/offline.mjs';
import {preserveExternal} from '../operator/policy.mjs';
import {readDependencyInputs} from '../operator/dependency-inputs.mjs';
const root=resolve(import.meta.dirname,'..'),h=n=>String(n).repeat(64);
const graph=()=>({schema:1,roots:{'@deepseek-ai/dsh':'p1','dsh-system-enhancement-package':'p2','@deepseek-ai/dsh-desktop':'p3','@deepseek-ai/dsh-client-ui-settings-general':'p4','user-plugin':'p5'},packages:[{id:'p1',name:'@deepseek-ai/dsh',version:'0.2.0-rc.2',dependencies:{}},{id:'p2',name:'dsh-system-enhancement-package',version:'0.2.1-beta.1',dependencies:{}},{id:'p3',name:'@deepseek-ai/dsh-desktop',version:'0.2.0-rc.2',dependencies:{}},{id:'p4',name:'@deepseek-ai/dsh-client-ui-settings-general',version:'0.2.0-rc.2',dependencies:{}},{id:'p5',name:'user-plugin',version:'1.0.0',dependencies:{}}],files:[{path:'store/p3/main.js',sha256:h(1),size:10},{path:'store/p4/client.js',sha256:h(2),size:20},{path:'store/p5/index.js',sha256:h(3),size:30}]});
function fixture(){const before=graph(),after=structuredClone(before);after.packages[1].version='0.2.1-beta.2';after.files[0]={...after.files[0],sha256:h(4),size:11};after.files[1]={...after.files[1],sha256:h(5),size:21};after.files.push({path:'store/p4/new-filter.js',sha256:h(6),size:31});const contract={schema:1,kind:'exact-same-host-file-contract',hostVersion:'0.2.0-rc.2',fromSepVersion:'0.2.1-beta.1',sepVersion:'0.2.1-beta.2',packageChanges:[{id:'p2',before:before.packages[1],after:after.packages[1]}],changes:[{path:before.files[0].path,packageName:'@deepseek-ai/dsh-desktop',before:before.files[0],after:after.files[0]},{path:before.files[1].path,packageName:'@deepseek-ai/dsh-client-ui-settings-general',before:before.files[1],after:after.files[1]},{path:after.files[3].path,packageName:'@deepseek-ai/dsh-client-ui-settings-general',before:null,after:after.files[3]}]};return{before,after,contract};}
test('allows exact desktop/general replacements and a listed general addition',()=>{const f=fixture();assert.deepEqual(verifyExactGraph(f.before,f.after,f.contract),{status:'pass',changedFiles:3,changedPackageIds:['p3','p4','p2']});});
test('rejects an undeclared changed desktop file',()=>{const f=fixture();f.contract.changes.shift();assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_UNLISTED_FILE'});});
test('rejects an undeclared general addition',()=>{const f=fixture();f.contract.changes.pop();assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_UNLISTED_FILE'});});
test('rejects a listed user package program change',()=>{const f=fixture(),old=f.before.files[2],next={...old,sha256:h(7)};f.after.files[2]=next;f.contract.changes.push({path:old.path,packageName:'user-plugin',before:old,after:next});assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_OWNER'});});
test('rejects a removal even when the owner and file are listed',()=>{const f=fixture(),old=f.before.files[0];f.after.files=f.after.files.filter(x=>x.path!==old.path);f.contract.changes[0].after=null;assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_REMOVAL_NOT_REVIEWED'});});
test('rejects wrong before bytes and wrong after bytes',()=>{for(const field of ['before','after']){const f=fixture();f.contract.changes[0][field]={...f.contract.changes[0][field],sha256:h(8)};assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_FILE_BINDING'});}});
test('rejects a fake owner on a listed change',()=>{const f=fixture();f.contract.changes[1].packageName='@deepseek-ai/dsh-desktop';assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_OWNER'});});
test('rejects dependency topology and package set changes',()=>{const f=fixture();f.after.packages[2].dependencies={evil:'p5'};assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_TOPOLOGY'});const g=fixture();g.after.packages.push({id:'p6',name:'rogue',version:'1',dependencies:{}});assert.throws(()=>verifyExactGraph(g.before,g.after,g.contract),{code:'EXACT_PACKAGE_SET'});});
test('rejects changed versions rather than relabeling the host or SEP',()=>{for(const field of ['hostVersion','fromSepVersion','sepVersion']){const f=fixture();f.contract[field]='99.0.0';assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_VERSION'});}});
test('rejects duplicate and unsafe addition paths',()=>{const f=fixture();f.contract.changes.push(f.contract.changes[0]);assert.throws(()=>verifyExactGraph(f.before,f.after,f.contract),{code:'EXACT_DUPLICATE_MAPPING'});const g=fixture();g.after.files[3].path='store/p4/../evil.js';assert.throws(()=>verifyExactGraph(g.before,g.after,g.contract),{code:'EXACT_PATH'});});
function preserved(){const f=fixture(),plugin={kind:'plugin-instance',instanceId:'external:custom',source:'external',name:'private-user-plugin',fingerprint:h(7),enabled:true,configFingerprint:digest({choice:'keep'}),activationFingerprint:h(8)};const row={id:plugin.instanceId,config:{choice:'keep'},enabled:true,activationFingerprint:h(8)};return{...f,current:{hardBlocks:[],plugins:[plugin]},candidate:{hardBlocks:[],plugins:[structuredClone(plugin)]},profile:{gaps:[],warnings:[],rows:[row]},nextProfile:{gaps:[],warnings:[],rows:[structuredClone(row)]},oldRoot:'D:/fixture-old',newRoot:'D:/fixture-new'};}
test('preserves a configured external user plugin through the program change',()=>{assert.deepEqual(verifyInventoryPreservation(preserved()),[]);});
test('rejects user plugin disablement and fingerprint changes',()=>{for(const mutation of [p=>p.enabled=false,p=>p.fingerprint=h(9)]){const f=preserved();mutation(f.candidate.plugins[0]);assert.throws(()=>verifyInventoryPreservation(f),/EXACT_INSTANCE_CONFIG|EXACT_INSTANCE_CHANGED/);assert.throws(()=>preserveExternal(f.current.plugins,f.candidate.plugins),/HOST_EXTERNAL_PLUGIN_CHANGED/);}});
test('rejects plugin removal and config rewrites',()=>{const f=preserved();f.candidate.plugins=[];assert.throws(()=>verifyInventoryPreservation(f),{code:'EXACT_INSTANCE_SET'});const g=preserved();g.nextProfile.rows[0].config.choice='overwrite';assert.throws(()=>verifyInventoryPreservation(g),{code:'EXACT_PROFILE_ROWS'});});
test('requires exact plan report and graph consent',()=>{const expected={planHash:h(1),reportHash:h(2),graphHash:h(3)};for(const c of [null,{accepted:false,...expected},...Object.keys(expected).map(k=>({accepted:true,...expected,[k]:h(4)}))])assert.throws(()=>validatePlanConsent(expected,c),/SEP_PLAN_CONSENT/);validatePlanConsent(expected,{accepted:true,acceptedCompatibilityRisk:true,...expected});});
test('verifies the copied full dependency closure and actual aliases',async()=>{assert.equal((await readDependencyInputs()).length,1510);});


test("does not accept unknown compatibility risk implicitly",()=>{assert.throws(()=>validatePlanConsent({planHash:h(1),reportHash:h(2),graphHash:h(3)},{accepted:true,planHash:h(1),reportHash:h(2),graphHash:h(3)}),/SEP_PLAN_CONSENT/);});
