import test,{after} from 'node:test';import assert from 'node:assert/strict';import {existsSync,mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL,fileURLToPath} from 'node:url';import {Window} from 'happy-dom';import React,{act} from 'react';import {createRoot} from 'react-dom/client';
const window=new Window();for(const k of ['window','document','HTMLElement','HTMLInputElement','Event','MouseEvent','Node'])globalThis[k]=k==='window'?window:window[k];globalThis.IS_REACT_ACT_ENVIRONMENT=true;after(()=>window.close());
let Component;const file=new URL('../src/client/AssessmentSettingsSection.tsx',import.meta.url);if(existsSync(file)){const esbuild=await import('esbuild'),out=join(mkdtempSync(fileURLToPath(new URL('./.runtime-assessment-',import.meta.url))),'component.mjs');await esbuild.build({entryPoints:[fileURLToPath(file)],outfile:out,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime'],loader:{'.css':'empty'},tsconfigRaw:{compilerOptions:{jsx:'react-jsx'}}});Component=(await import(pathToFileURL(out))).AssessmentSettingsSection;}
const data=()=>({version:1,available:true,enabled:false,latest:{target:'0.2.1',status:'blocked',phase:'complete',analysis:'pass',review:'fail',reason:'REVIEW_CONFLICT',summary:'Conflicting evidence',plugins:[{name:'my-plugin',version:'1',verdict:'unknown',reasons:['noCandidate']}]},usage:{reportedRequests:2,promptTokens:200,completionTokens:40,estimatedCny:.001,reservedCny:0,isProviderInvoice:false}});
async function mount(api){assert.equal(typeof Component,'function','settings component exists');const div=document.createElement('div');document.body.append(div);const root=createRoot(div);await act(async()=>{root.render(React.createElement(Component,{api,requestTimeoutMs:1000,useConnection:()=>0,t:k=>k}));await new Promise(r=>setTimeout(r,10));});return {div,close:async()=>{await act(()=>root.unmount());div.remove();}};}
test('independent default-off switch displays token warning and review state',async()=>{const v=await mount({get:async()=>data()});try{assert.equal(v.div.querySelector('[role=switch]').checked,false);assert.match(v.div.textContent,/costHelp/);assert.match(v.div.textContent,/0.2.1/);assert.match(v.div.textContent,/200/);assert.match(v.div.textContent,/notInstallable/);assert.match(v.div.textContent,/my-plugin/);assert.match(v.div.textContent,/noCandidate/);}finally{await v.close();}});
test('saving switch persists through API and keeps its report visible',async()=>{let enabled=false;const v=await mount({get:async()=>({...data(),enabled}),update:async value=>{enabled=value;return {...data(),enabled};}});try{await act(async()=>{v.div.querySelector('[role=switch]').click();await new Promise(r=>setTimeout(r,10));});assert.equal(enabled,true);assert.equal(v.div.querySelector('[role=switch]').checked,true);assert.match(v.div.textContent,/my-plugin/);}finally{await v.close();}});

test('unknown usage is not displayed as zero actual model consumption',async()=>{const value=data();value.usage={...value.usage,reportedRequests:0,promptTokens:0,completionTokens:0,reservedCny:.02};const v=await mount({get:async()=>value});try{assert.match(v.div.textContent,/unreported/);assert.match(v.div.textContent,/0.020000/);}finally{await v.close();}});
