import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,mkdtemp,copyFile,realpath} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
const exec=promisify(execFile),work=await realpath(resolve(import.meta.dirname,'..')),project=resolve(work,'../..');
const files=['p0500/src/controller.mjs','p0500/src/guardian.mjs','p0500/src/server.mjs','p0500/src/owner-lease.mjs','p0501/src/store.js','p0501/src/p2/control.js','p0501/src/owner-lease.mjs'];
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
test('actual core generator plus journal gate reproduces sealed overlay in a fresh temporary directory',async()=>{
 const before=await Promise.all(files.map(async name=>({name,sha256:hash(await readFile(join(work,'core/overlay',name)))})));
 const tmp=await mkdtemp(join(work,'core-regeneration-'));
 for(const dir of ['managed','ownership'])await mkdir(join(tmp,dir));
 for(const name of ['managed/guardian-lifecycle-transform.mjs','ownership/owner-file.mjs','ownership/apply-journal-gate.mjs'])await copyFile(join(work,name),join(tmp,name));
 let source=await readFile(join(work,'integrate-core.mjs'),'utf8');
 const anchor="const project=await fs.realpath(path.resolve(import.meta.dirname,'../..'));";
 assert.equal(source.split(anchor).length,2);
 // Only relocate the baseline root; all output paths remain relative to this
 // fresh test copy, and every actual transformation runs unchanged.
 source=source.replace(anchor,'const project='+JSON.stringify(project)+';');
 await writeFile(join(tmp,'integrate-core.mjs'),source);
 const logs=[];
 for(const entry of ['integrate-core.mjs','ownership/apply-journal-gate.mjs']){const r=await exec(process.execPath,[join(tmp,entry)],{windowsHide:true,timeout:60000,maxBuffer:1024*1024});logs.push({entry,stdout:r.stdout,stderr:r.stderr});}
 const compared=[];
 for(const saved of before){
  const regenerated=hash(await readFile(join(tmp,'core/overlay',saved.name)));
  assert.equal(regenerated,saved.sha256,saved.name+' generated bytes drifted');
  assert.equal(hash(await readFile(join(work,'core/overlay',saved.name))),saved.sha256,'sealed overlay changed');
  compared.push({...saved,regenerated});
 }
 await writeFile(join(tmp,'result.json'),JSON.stringify({schema:1,status:'pass',scope:'source generation consistency only; no runtime behavior change',logs,compared},null,2)+'\n');
 console.log(JSON.stringify({status:'pass',evidence:join(tmp,'result.json')}));
});
