import {readFile,writeFile,mkdir,readdir,lstat,realpath} from 'node:fs/promises';
import {join,resolve,dirname,isAbsolute,relative,sep} from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const sha=b=>createHash('sha256').update(b).digest('hex');
const fail=c=>{throw Object.assign(Error(c),{code:c});};
const demand=(v,c)=>{if(!v)fail(c);};
export function safePath(p){demand(typeof p==='string'&&p&&p.split('/').every(x=>x&&x!=='.'&&x!=='..'&&!/[\\<>:"|?*\x00-\x1f]/.test(x)&&!/[. ]$/.test(x)),'PATH_INVALID');return p;}
const jread=async p=>JSON.parse(await readFile(p,'utf8'));
const put=async(p,b)=>{await mkdir(dirname(p),{recursive:true});await writeFile(p,b);};
const jput=(p,v)=>put(p,JSON.stringify(v,null,2)+'\n');
async function checked(p,row){const s=await lstat(p);demand(s.isFile()&&!s.isSymbolicLink()&&s.nlink===1,'FILE_IDENTITY');const b=await readFile(p);demand((row.size===undefined||b.length===row.size)&&sha(b)===row.sha256,'CONTENT_CHANGED');return b;}
async function absent(p){try{await lstat(p);fail('DESTINATION_EXISTS');}catch(e){if(e.code!=='ENOENT')throw e;}}
async function list(root,prefix=''){const out=[];for(const e of await readdir(join(root,prefix),{withFileTypes:true})){const path=prefix?prefix+'/'+e.name:e.name;safePath(path);demand(!e.isSymbolicLink(),'INPUT_LINK');if(e.isDirectory())out.push(...await list(root,path));else {const b=await readFile(join(root,path));out.push({path,size:b.length,sha256:sha(b)});}}return out.sort((a,b)=>a.path.localeCompare(b.path));}
const inside=(a,b)=>{const r=relative(a,b);return r===''||(!r.startsWith('..'+sep)&&r!=='..'&&!isAbsolute(r));};
export async function buildDistribution(c){
 demand(c.schema===1&&/^[a-zA-Z0-9._-]{1,80}$/.test(c.revision),'CONFIG');
 for(const field of ['baseRoot','outputRoot','bootstrapRoot'])demand(isAbsolute(c[field]??''),'CONFIG_PATH');
 await absent(c.outputRoot);demand(!inside(c.baseRoot,c.outputRoot)&&!inside(c.outputRoot,c.baseRoot),'DESTINATION_OVERLAP');
 demand((await realpath(c.baseRoot)).toLowerCase()===resolve(c.baseRoot).toLowerCase(),'BASE_ALIAS');
 const names=['DSH-SEP-Full','DSH-SEP-Only'],gb=await readFile(join(c.baseRoot,names[0],'graph.json'));
 demand(sha(gb)===c.expectedBaseGraph,'BASE_GRAPH');const graph=JSON.parse(gb),old=new Map(graph.files.map(f=>[safePath(f.path),f]));
 const boot=new Map(),seenBoot=new Set();for(const f of c.bootstrapFiles){safePath(f.path);demand(!seenBoot.has(f.path.toLowerCase()),'BOOTSTRAP_DUPLICATE');seenBoot.add(f.path.toLowerCase());boot.set(f.path,await checked(join(c.bootstrapRoot,f.path),f));}
 for(const p of ['launcher.mjs','launch.mjs','start.vbs','start.ps1'])demand(boot.has(p),'BOOTSTRAP_MISSING');
 const changes=new Map();for(const f of c.overlay??[]){safePath(f.path);demand(/^store\/p\d+\//.test(f.path)&&graph.packages.some(p=>p.id===f.path.split('/')[1]),'OVERLAY_PATH');demand(!changes.has(f.path),'OVERLAY_DUPLICATE');demand((old.get(f.path)?.sha256??null)===(f.beforeSha256??null),'OVERLAY_BASE');changes.set(f.path,await checked(join(c.overlayRoot,f.path),f));}
 // Validate all base input bytes before creating any output. The same bytes are
 // checked once more immediately before their copy into the new candidate.
 const manifests=[];for(const name of names){const r=join(c.baseRoot,name),m=await jread(join(r,'manifest.json'));demand(sha(await readFile(join(r,'graph.json')))===c.expectedBaseGraph&&m.graph.sha256===c.expectedBaseGraph,'BASE_GRAPH');const selected=new Set(m.payload);for(const f of graph.files)if(m.kind==='full'||selected.has(f.path))await checked(join(r,'payload',safePath(f.path)),f);for(const f of m.support)await checked(join(r,safePath(f.path)),f);manifests.push(m);}
 const srcRoot=join(c.baseRoot,'DSH-SEP-Source'),srcFiles=await list(srcRoot);demand(!srcFiles.some(f=>/(^|\/)(?:\.git|\.env|\.codex)(\/|$)/.test(f.path)),'SOURCE_PRIVATE_PATH');
 const repairPolicy=c.repairPolicy?JSON.parse(await checked(c.repairPolicy.path,c.repairPolicy)):null;
 for(const [path,b]of changes)old.set(path,{path,size:b.length,sha256:sha(b)});graph.files=[...old.values()].sort((a,b)=>a.path.localeCompare(b.path));const newgb=JSON.stringify(graph,null,2)+'\n',graphHash=sha(newgb);
 await mkdir(c.outputRoot);await jput(join(c.outputRoot,'BUILDING.json'),{schema:1,revision:c.revision,baseGraphSha256:c.expectedBaseGraph});
 if(repairPolicy){demand(repairPolicy.targetGraph==='@GRAPH_HASH@'||repairPolicy.targetGraph===graphHash,'REPAIR_POLICY_GRAPH');repairPolicy.targetGraph=graphHash;}
 for(let i=0;i<names.length;i++){const name=names[i],root=join(c.outputRoot,name),base=join(c.baseRoot,name),m=structuredClone(manifests[i]);await mkdir(root);for(const f of manifests[i].support)await put(join(root,f.path),await checked(join(base,f.path),f));const selected=new Set(m.payload);for(const [path]of changes)selected.add(path);for(const f of graph.files){if(m.kind!=='full'&&!selected.has(f.path))continue;await put(join(root,'payload',f.path),changes.has(f.path)?changes.get(f.path):await checked(join(base,'payload',f.path),f));}for(const [p,b]of boot)await put(join(root,'bootstrap',p),b);await put(join(root,'installer.mjs'),await readFile(join(import.meta.dirname,'installer.mjs')));if(repairPolicy){await jput(join(root,'repair-policy.json'),repairPolicy);for(const rp of ['repair.ps1','REPAIR_README.md'])await put(join(root,rp),await readFile(join(import.meta.dirname,rp)));for(const rp of ['build.mjs','repair.mjs','repair-cli.mjs','windows-adapters.mjs'])await put(join(root,'repair',rp),await readFile(join(import.meta.dirname,rp)));}await put(join(root,'launcher.mjs'),boot.get('launcher.mjs'));await put(join(root,'start.vbs'),boot.get('start.vbs'));await put(join(root,'graph.json'),newgb);m.graph={size:Buffer.byteLength(newgb),sha256:graphHash};m.distributionRevision=c.revision;m.payload=[...selected].sort();m.bootstrap={schema:1,files:[...boot].map(([path,b])=>({path,size:b.length,sha256:sha(b)}))};const ha=await jread(join(root,'host-adaptations.json'));for(const f of ha)if(old.has(f.path))f.afterSha256=old.get(f.path).sha256;await jput(join(root,'host-adaptations.json'),ha);m.support=(await list(root)).filter(f=>!f.path.startsWith('payload/')&&!['manifest.json','graph.json'].includes(f.path));await jput(join(root,'manifest.json'),m);}
 const source=join(c.outputRoot,'DSH-SEP-Source');for(const f of srcFiles)await put(join(source,f.path),await checked(join(srcRoot,f.path),f));const sm=await jread(join(source,'SOURCE_FILES.json'));const rows=new Map(sm.files.map(f=>[f.path,f]));for(const f of sm.files)if(f.role==='exact-release-file'&&f.graphPath&&changes.has(f.graphPath)){const b=changes.get(f.graphPath);await put(join(source,f.path),b);rows.set(f.path,{...f,sha256:sha(b),bytes:b.length});}for(const [path,b]of changes){const p='program-source/'+path;await put(join(source,p),b);rows.set(p,{path:p,graphPath:path,role:'exact-release-file',graphMatch:true,sha256:sha(b),bytes:b.length});}for(const [path,b]of boot){const p='bootstrap/'+path;await put(join(source,p),b);rows.set(p,{path:p,role:'exact-bootstrap-file',sha256:sha(b),bytes:b.length});}for(const p of ['build.mjs','installer.mjs','repair.mjs','repair-cli.mjs','windows-adapters.mjs','build.test.mjs','repair.test.mjs','installer.test.mjs','windows-adapters.test.mjs','repair.ps1','REPAIR_README.md','IMPLEMENTATION.md','make-policy.mjs']){const b=await readFile(join(import.meta.dirname,p)),path='distribution/'+p;await put(join(source,path),b);rows.set(path,{path,role:'distribution-source',sha256:sha(b),bytes:b.length});}await put(join(source,'graph.json'),newgb);await jput(join(source,'SOURCE_FILES.json'),{...sm,distribution:c.revision,graphSha256:graphHash,summary:{graphSha256:graphHash,files:rows.size,exactReleaseFiles:[...rows.values()].filter(f=>f.role==='exact-release-file').length,supplementalFiles:[...rows.values()].filter(f=>f.role!=='exact-release-file').length,bytes:[...rows.values()].reduce((n,f)=>n+(f.bytes??0),0)},files:[...rows.values()].sort((a,b)=>a.path.localeCompare(b.path))});
 const result={schema:1,status:'pass',revision:c.revision,baseGraphSha256:c.expectedBaseGraph,graphHash,graphChanges:[...changes].map(([path,b])=>({path,sha256:sha(b)})),bootstrapFiles:[...boot].map(([path,b])=>({path,sha256:sha(b)})),scope:'Unarchived candidate assembly only; publication documentation and final archive tests remain required.'};await jput(join(c.outputRoot,'BUILD-RESULT.json'),result);return result;
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const [flag,path]=process.argv.slice(2);if(flag!=='--config'||!isAbsolute(path??''))throw Error('Usage: node build.mjs --config <absolute-config.json>');console.log(JSON.stringify(await buildDistribution(await jread(path))));}
