import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,mkdir,writeFile,readFile,lstat,symlink,realpath}from'node:fs/promises';import{join}from'node:path';import{tmpdir}from'node:os';
const subject=await import('./native-assembly.mjs').catch(()=>null);
async function fixture(){const root=await realpath(await mkdtemp(join(tmpdir(),'sep-native-assembly-')));const pkg=join(root,'input');await mkdir(join(pkg,'lib'),{recursive:true});await writeFile(join(pkg,'package.json'),JSON.stringify({name:'probe',version:'1.0.0',main:'lib/index.js',files:['lib']}));await writeFile(join(pkg,'lib/index.js'),'export const value=1;');return{root,pkg,destination:join(root,'program')}}
const listFiles=async()=>['package.json','lib/index.js'];
test('creates a sealed independent program and links only inside its store',async()=>{assert.ok(subject,'native assembly implementation exists');const f=await fixture();const r=await subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles});const p=r.graph.packages[0];assert.equal(await realpath(join(f.destination,'node_modules/probe')),join(f.destination,'store',p.id));assert.equal((await lstat(join(f.destination,'store',p.id,'lib/index.js'))).nlink,1);assert.ok(r.graph.files.every(f=>[0o644,0o755].includes(f.mode)));await writeFile(join(f.pkg,'lib/index.js'),'changed');assert.match(await readFile(join(f.destination,'store',p.id,'lib/index.js'),'utf8'),/value=1/)});
test('an existing output directory is rejected without changing it',async()=>{assert.ok(subject);const f=await fixture();await mkdir(f.destination);await writeFile(join(f.destination,'keep'),'x');await assert.rejects(()=>subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles}),/ASSEMBLY_DESTINATION_EXISTS/);assert.equal(await readFile(join(f.destination,'keep'),'utf8'),'x')});
test('missing required dependency fails before destination is created',async()=>{assert.ok(subject);const f=await fixture();await writeFile(join(f.pkg,'package.json'),JSON.stringify({name:'probe',version:'1.0.0',dependencies:{missing:'1.0.0'}}));await assert.rejects(()=>subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles}),/ASSEMBLY_DEPENDENCY_MISSING/);await assert.rejects(()=>lstat(f.destination),{code:'ENOENT'})});
test('path traversal from a file selector is rejected',async()=>{assert.ok(subject);const f=await fixture();await assert.rejects(()=>subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles:async()=>['package.json','../outside']}),/ASSEMBLY_FILE_PATH/)});
test('credential files are rejected even if a package lists them',async()=>{assert.ok(subject);const f=await fixture();await writeFile(join(f.pkg,'.env'),'secret');await assert.rejects(()=>subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles:async()=>['package.json','.env']}),/ASSEMBLY_PRIVATE_FILE/)});
test('required dependencies are copied with their local package links',async()=>{assert.ok(subject);const f=await fixture(),child=join(f.pkg,'node_modules/child');await mkdir(join(child,'lib'),{recursive:true});await writeFile(join(child,'package.json'),JSON.stringify({name:'child',version:'2.0.0'}));await writeFile(join(child,'lib/index.js'),'child');await writeFile(join(f.pkg,'package.json'),JSON.stringify({name:'probe',version:'1.0.0',dependencies:{child:'2.0.0'}}));const r=await subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles});assert.equal(r.graph.packages.length,2);const parent=r.graph.packages.find(p=>p.name==='probe');assert.equal(await realpath(join(f.destination,'store',parent.id,'node_modules/child')),join(f.destination,'store',parent.dependencies.child))});
test('npm packlist leading dot prefix is accepted without accepting parent traversal',async()=>{assert.ok(subject);const f=await fixture();const r=await subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles:async()=>['package.json','./lib/index.js']});assert.ok(r.graph.files.some(p=>p.path.endsWith('/lib/index.js')));const g=await fixture();await assert.rejects(()=>subject.assembleNativeProgram({roots:{probe:g.pkg},destination:g.destination,listFiles:async()=>['package.json','./../outside']}),/ASSEMBLY_FILE_PATH/)});
test('explicit runtime bridge resolves loader-owned binding and rejects missing targets',async()=>{const f=await fixture();await writeFile(join(f.pkg,'package.json'),JSON.stringify({name:'probe',version:'1.0.0',dependencies:{loader:'1.0.0',binding:'1.0.0'}}));for(const name of ['loader','binding']){const at=join(f.pkg,'node_modules',name);await mkdir(join(at,'lib'),{recursive:true});await writeFile(join(at,'package.json'),JSON.stringify({name,version:'1.0.0',main:'lib/index.js'}));await writeFile(join(at,'lib/index.js'),name==='loader'?'module.exports=require("binding")':'module.exports=42');}const r=await subject.assembleNativeProgram({roots:{probe:f.pkg},destination:f.destination,listFiles,runtimeLinks:[{from:'loader',to:'binding',version:'1.0.0'}]});const {createRequire}=await import('node:module');const loader=r.graph.packages.find(p=>p.name==='loader');assert.equal(createRequire(join(f.destination,'store',loader.id,'lib/index.js'))('binding'),42);const bad=await fixture();await assert.rejects(()=>subject.assembleNativeProgram({roots:{probe:bad.pkg},destination:bad.destination,listFiles,runtimeLinks:[{from:'probe',to:'missing',version:'1.0.0'}]}),/ASSEMBLY_RUNTIME_LINK/)});