import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const dir=fileURLToPath(new URL('.',import.meta.url)),root=resolve(dir,'../../..');
const baseline=join(root,'deliverables/DSH-SEP-Windows-Alpha-20260921-MIT/DSH-SEP-Full/payload/store/p0498/lib/index.js');
const sourcePath=join(root,'dsh-host-isolation/candidates/dsh-alpha2-migration-20260917/source/deepseek-harness-ddefc45fbc7f8e46dd73185e68295696d1297887/apps/desktop-host/src/index.ts');
const replace=(s,a,b)=>{if(s.split(a).length!==2)throw Error('PATCH_ANCHOR_CHANGED: '+a.slice(0,80));return s.replace(a,b);};
let js=await readFile(baseline,'utf8'),ts=await readFile(sourcePath,'utf8');
js='import {createHostLifecycle} from "./sep-host-lifecycle.mjs";\n'+js.replace('//# sourceMappingURL=index.js.map','// Corresponding reviewed TypeScript is bound in overlay-manifest.json.');
js=replace(js,'  const version = JSON.parse(await readFile2','  const lifetime = createHostLifecycle({managed});\n  try {\n  const version = JSON.parse(await readFile2');
js=replace(js,'  const application = runProfile({','  const application = lifetime.startApplication(() => runProfile({');
js=replace(js,'  });\n  let stopping;','  }));');
const begin=js.indexOf('  const send = (message) => new Promise'),end=js.indexOf('  process.on("message", (message) => {',begin);
if(begin<0||end<0)throw Error('PATCH_ANCHOR_CHANGED: stop');
js=js.slice(0,begin)+'  const send = lifetime.send;\n'+js.slice(end);
js=replace(js,'    if (message.type === "shutdown") {\n      void stop();\n      return;\n    }\n','');
js=replace(js,'if (stopping !== void 0 || control.updateTasks === void 0)','if (lifetime.stopping || control.updateTasks === void 0)');
js=replace(js,'  process.once("disconnect", () => {\n    void stop();\n  });\n','');
js=replace(js,'  const { ctx } = await application;','  const { ctx } = await application;\n  lifetime.assertActive();');
js=replace(js,'  const url = ctx.connection.authenticatedUrl','  lifetime.assertActive();\n  const url = ctx.connection.authenticatedUrl');
js=replace(js,'  if (process.connected) process.send?.({\n    type: "ready",','  await lifetime.publishReady({\n    type: "ready",');
js=replace(js,'  }, (error) => {\n    if (error !== null) console.error(error);\n  });\n}\nif (import.meta.main)','  });\n  } catch (error) {\n    await lifetime.startupFailed(error);\n    if (error?.code !== "SEP_HOST_STOPPING") throw error;\n  }\n}\nif (import.meta.main)');
ts="import {createHostLifecycle} from './sep-host-lifecycle.mjs'\n"+ts;
ts=replace(ts,"  const version = (JSON.parse(await readFile", "  const lifetime = createHostLifecycle({managed})\n  try {\n  const version = (JSON.parse(await readFile");
ts=replace(ts,'  const application = runProfile({','  const application = lifetime.startApplication(() => runProfile({');
ts=replace(ts,'  })\n  let stopping: Promise<void> | undefined','  }))');
const tb=ts.indexOf('  const send = (message: object): Promise<void> => new Promise'),te=ts.indexOf("  process.on('message', (message: unknown) => {",tb);
if(tb<0||te<0)throw Error('PATCH_ANCHOR_CHANGED: TS stop');
ts=ts.slice(0,tb)+'  const send = lifetime.send\n'+ts.slice(te);
ts=replace(ts,"    if (message.type === 'shutdown') { void stop(); return }\n",'');
ts=replace(ts,'if (stopping !== undefined || control.updateTasks === undefined)','if (lifetime.stopping || control.updateTasks === undefined)');
ts=replace(ts,"  process.once('disconnect', () => { void stop() })\n",'');
ts=replace(ts,'  const { ctx } = await application','  const { ctx } = await application\n  lifetime.assertActive()');
ts=replace(ts,'  const url = ctx.connection.authenticatedUrl','  lifetime.assertActive()\n  const url = ctx.connection.authenticatedUrl');
ts=replace(ts,"  if (process.connected) process.send?.({ type: 'ready'","  await lifetime.publishReady({ type: 'ready'");
ts=replace(ts,"  }, (error) => { if (error !== null) console.error(error) })\n}","  })\n  } catch (error) {\n    await lifetime.startupFailed(error)\n    if ((error as { code?: string })?.code !== 'SEP_HOST_STOPPING') throw error\n  }\n}");
const lib=join(dir,'overlay/p0498/lib'),src=join(dir,'source/apps/desktop-host/src');
await mkdir(lib,{recursive:true});await mkdir(src,{recursive:true});
await writeFile(join(lib,'index.js'),js);await writeFile(join(src,'index.ts'),ts);
for(const d of [lib,src])await copyFile(join(dir,'sep-host-lifecycle.mjs'),join(d,'sep-host-lifecycle.mjs'));
await copyFile(join(dir,'sep-host-lifecycle.d.mts'),join(src,'sep-host-lifecycle.d.mts'));
for(const [input,output] of [[join(baseline,'../../package.json'),join(lib,'../package.json')],[join(sourcePath,'../../package.json'),join(src,'../package.json')]]){
 const p=JSON.parse(await readFile(input,'utf8'));if(!p.files.includes('lib/sep-host-lifecycle.mjs'))p.files.push('lib/sep-host-lifecycle.mjs');await writeFile(output,JSON.stringify(p,null,2)+'\n');
}
const sha=b=>createHash('sha256').update(b).digest('hex');
const files=[baseline,sourcePath,join(dir,'sep-host-lifecycle.mjs'),join(lib,'index.js'),join(src,'index.ts'),join(lib,'../package.json'),join(src,'../package.json'),join(src,'sep-host-lifecycle.d.mts')];
await writeFile(join(dir,'overlay-manifest.json'),JSON.stringify({schema:1,files:await Promise.all(files.map(async path=>({path,sha256:sha(await readFile(path))})))},null,2)+'\n');
console.log(JSON.stringify({status:'pass',overlay:lib,source:src}));
