import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,access} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {buildDistribution} from './build.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
const put=async(p,b)=>{await mkdir(join(p,'..'),{recursive:true});await writeFile(p,b);};
const jput=(p,v)=>put(p,JSON.stringify(v,null,2)+'\n');
async function fixture(){const root=await mkdtemp(join(tmpdir(),'sep-distribution-'));const base=join(root,'base'),output=join(root,'output'),boot=join(root,'bootstrap'),overlay=join(root,'overlay');const path='store/p0500/src/managed.mjs',bytes=Buffer.from('export const version=1;\n');const graph={kind:'dsh-sep-local-offline-graph',packages:[{id:'p0500',name:'@deepseek-ai/dsh-recovery',version:'1',dependencies:{}}],roots:{'@deepseek-ai/dsh-recovery':'p0500'},files:[{path,size:bytes.length,sha256:sha(bytes)}]};const gb=JSON.stringify(graph,null,2)+'\n';for(const name of ['DSH-SEP-Full','DSH-SEP-Only']){await put(join(base,name,'graph.json'),gb);await put(join(base,name,'payload',path),bytes);await put(join(base,name,'README.md'),'baseline documentation');await jput(join(base,name,'host-adaptations.json'),[]);await jput(join(base,name,'manifest.json'),{schema:1,kind:name.endsWith('Full')?'full':'sep',graph:{size:Buffer.byteLength(gb),sha256:sha(gb)},payload:[path],support:[{path:'README.md',size:22,sha256:sha('baseline documentation')},{path:'host-adaptations.json',size:3,sha256:sha('[]\n')}]});}await put(join(base,'DSH-SEP-Source/program-source',path),bytes);await jput(join(base,'DSH-SEP-Source/SOURCE_FILES.json'),{files:[{path:'program-source/'+path,graphPath:path,role:'exact-release-file',sha256:sha(bytes),bytes:bytes.length}]});const files={'launcher.mjs':'export const graph="@GRAPH_HASH@";','launch.mjs':'import "./managed/launcher.mjs";','start.vbs':'bootstrap vbs','start.ps1':'bootstrap powershell','startup-lease.mjs':'export const lease=true;'};for(const [p,b]of Object.entries(files))await put(join(boot,p),b);await put(join(overlay,path),'export const version=2;\n');const cfg={schema:1,baseRoot:base,outputRoot:output,revision:'test-startup',expectedBaseGraph:sha(gb),bootstrapRoot:boot,bootstrapFiles:Object.entries(files).map(([path,b])=>({path,sha256:sha(b)})),overlayRoot:overlay,overlay:[{path,beforeSha256:sha(bytes),sha256:sha('export const version=2;\n')}]};return {root,base,output,boot,overlay,cfg,path};}
test('builder gives both installers the full bootstrap closure and graph-matching source; baseline remains intact',async()=>{const f=await fixture();const result=await buildDistribution(f.cfg);assert.equal(result.status,'pass');for(const name of ['DSH-SEP-Full','DSH-SEP-Only']){const m=JSON.parse(await readFile(join(f.output,name,'manifest.json')));assert.equal(await readFile(join(f.output,name,'payload',f.path),'utf8'),'export const version=2;\n');assert(m.support.some(x=>x.path==='bootstrap/startup-lease.mjs'));assert(m.bootstrap.files.some(x=>x.path==='startup-lease.mjs'));}assert.equal(await readFile(join(f.output,'DSH-SEP-Source/program-source',f.path),'utf8'),'export const version=2;\n');assert.equal(await readFile(join(f.output,'DSH-SEP-Source/bootstrap/startup-lease.mjs'),'utf8'),'export const lease=true;');assert.equal(await readFile(join(f.base,'DSH-SEP-Full/payload',f.path),'utf8'),'export const version=1;\n');});
test('invalid overlay old hash rejects before creating output',async()=>{const f=await fixture();f.cfg.overlay[0].beforeSha256='0'.repeat(64);await assert.rejects(buildDistribution(f.cfg),/OVERLAY_BASE/);await assert.rejects(access(f.output));});
test('overlay cannot modify unlisted user data',async()=>{const f=await fixture();f.cfg.overlay[0].path='../data/private.json';await assert.rejects(buildDistribution(f.cfg),/PATH|OVERLAY/);await assert.rejects(access(f.output));});
test('candidate destination is create-only',async()=>{const f=await fixture();await mkdir(f.output);await put(join(f.output,'personal.txt'),'keep');await assert.rejects(buildDistribution(f.cfg),/DESTINATION_EXISTS/);assert.equal(await readFile(join(f.output,'personal.txt'),'utf8'),'keep');});
test('case-colliding bootstrap names are rejected before any output exists',async()=>{const f=await fixture();const original={...f.cfg.bootstrapFiles[0]};f.cfg.bootstrapFiles[0].path='LAUNCHER.MJS';f.cfg.bootstrapFiles.push(original);await assert.rejects(buildDistribution(f.cfg),/BOOTSTRAP_DUPLICATE/);await assert.rejects(access(f.output));});
test('optional repair policy is bound to final graph and ships the PowerShell entry with source',async()=>{const f=await fixture();const path=join(f.root,'policy.json');await jput(path,{schema:1,targetGraph:'@GRAPH_HASH@',allowedProgramPaths:[],baselines:[]});f.cfg.repairPolicy={path,sha256:sha(await readFile(path))};const r=await buildDistribution(f.cfg);for(const name of ['DSH-SEP-Full','DSH-SEP-Only']){const root=join(f.output,name),m=JSON.parse(await readFile(join(root,'manifest.json'))),policy=JSON.parse(await readFile(join(root,'repair-policy.json')));assert.equal(policy.targetGraph,r.graphHash);assert(m.support.some(f=>f.path==='repair.ps1'));assert(m.support.some(f=>f.path==='repair/repair-cli.mjs'));}await access(join(f.output,'DSH-SEP-Source/distribution/repair.ps1'));});
