// Read only sealed public installer sources and the known local bootstrap;
// never reads credentials, memory, sessions or user plugin content.
import {readFile,writeFile,readdir,lstat} from 'node:fs/promises';
import {resolve,join} from 'node:path';import {createHash} from 'node:crypto';
const root=resolve(import.meta.dirname,'../../..'),work=resolve(import.meta.dirname,'..');
const sha=b=>createHash('sha256').update(b).digest('hex'),fail=c=>{throw Error(c);};
const read=async p=>{const s=await lstat(p);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1)fail('INPUT_IDENTITY');return readFile(p);};
const graph='8660c8d5ba2611ca676b0e6169705abd6843cce4a43cdccdea0bd0478a834e52',hotfix='7a1719d5bf7ce51a6973ab0f10d7532c1b0f2af086553adb7a438d08b1eb47a2';
const base=join(root,'deliverables/DSH-SEP-Windows-Alpha-20260921-MIT/DSH-SEP-Full'),oldInstaller=await read(join(base,'installer.mjs'));if(sha(oldInstaller)!=='c20b4a74000166c5319029986c0ff72697f9964c38a3a109ca4fd51b65f8a74b')fail('INSTALLER_CHANGED');
function generated(name){const pattern=new RegExp("await writeFile\\(join\\(destination,'"+name.replaceAll('.','\\.')+"'\\),(\"(?:\\\\.|[^\"\\\\])*\")\\);");const m=oldInstaller.toString().match(pattern);if(!m)fail('TEMPLATE_NOT_FOUND');return Buffer.from(JSON.parse(m[1]));}
const publicFiles={'launch.mjs':generated('launch.mjs'),'start.ps1':generated('start.ps1'),'start.vbs':await read(join(base,'start.vbs')),'managed/launcher.mjs':Buffer.from((await read(join(base,'launcher.mjs'))).toString().replaceAll('@GRAPH_HASH@',graph))};
const publicHashes=Object.fromEntries(Object.entries(publicFiles).map(([p,b])=>[p,sha(b)]));const installed=join(root,'work/release-20260921/validation/runs/mit-final-01/installations/full');for(const [p,h]of Object.entries(publicHashes))if(sha(await read(join(installed,p)))!==h)fail('PUBLIC_RENDER_MISMATCH');
const daily=join(root,'dsh-daily'),c=JSON.parse(await read(join(daily,'deployment-rc2.json')));if(c.graphHash!==hotfix||sha(await read(join(c.releaseRoot,'graph.json')))!==hotfix)fail('DAILY_GRAPH');
const prior=JSON.parse(await read(join(root,'work/daily-owner-recovery-20260924/deployment/receipt.json'))),dailyHashes={};for(const p of ['launch.mjs','start.vbs','start.ps1','managed-rc2/launcher.mjs','managed-rc2/startup-coordinator.mjs','managed-rc2/startup-lease.mjs','managed-rc2/cold-recovery/recover.mjs']){const full=join(daily,p),h=sha(await read(full)),receipt=prior.entries.find(e=>resolve(e.path).toLowerCase()===resolve(full).toLowerCase());if(p!=='start.ps1'&&receipt?.sha256!==h)fail('DAILY_BOOTSTRAP_CHANGED');dailyHashes[p]=h;}
async function paths(dir,prefix=''){const result=[];for(const e of await readdir(join(dir,prefix),{withFileTypes:true})){if(e.isSymbolicLink())fail('OVERLAY_LINK');const p=prefix?prefix+'/'+e.name:e.name;if(e.isDirectory())result.push(...await paths(dir,p));else result.push('store/'+p);}return result;}
const allow=new Set(['store/p0485/lib/sep-update/update-inventory.mjs']);for(const dir of ['core/overlay','managed/overlay','host-lifecycle/overlay','diagnostics/overlay'])for(const p of await paths(join(work,dir)))allow.add(p);
const policy={schema:1,targetGraph:'@GRAPH_HASH@',allowedProgramPaths:[...allow].sort(),baselines:[{graphHash:graph,layout:'managed',files:publicHashes},{graphHash:hotfix,layout:'managed-rc2',files:dailyHashes}]};
await writeFile(join(import.meta.dirname,'repair-policy.json'),JSON.stringify(policy,null,2)+'\n',{flag:'wx'});await writeFile(join(import.meta.dirname,'repair-policy-evidence.json'),JSON.stringify({status:'pass',scope:'Exact old public rendered templates compared with sealed ZIP-installed Full; exact known daily bootstrap compared with prior deployment receipt. No credentials read.',publicInstallerSha256:sha(oldInstaller),publicInstallationReference:'work/release-20260921/validation/runs/mit-final-01/installations/full',publicHashes,dailyHashes,allowedProgramPaths:policy.allowedProgramPaths,policySha256:sha(JSON.stringify(policy,null,2)+'\n')},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:'pass',baselines:2,publicFiles:Object.keys(publicHashes).length,dailyFiles:Object.keys(dailyHashes).length,overlayPaths:allow.size}));
